#
# Automatically generated make config: don't edit
# Dist builder
#
CONFIG_DISTVERSION="4.0"

#
# Library Configuration
#

#
# Force build (normally built when required)
#
# CONFIG_LIB_BITVECTOR is not set
# CONFIG_LIB_FLEX is not set
# CONFIG_LIB_BFD is not set
# CONFIG_LIB_LIBIBERTY is not set
# CONFIG_LIB_POPT is not set
CONFIG_LIB_LIBSSL=y
CONFIG_LIB_OPENSSL_FIPS=y
CONFIG_LIB_LIBGMP=y
CONFIG_LIB_LUA_LIBLUA=y
CONFIG_LIB_LUA_CURL=y
# CONFIG_LIB_LUA_LUAI2C is not set
# CONFIG_LIB_LIBG is not set
CONFIG_LIB_LIBGCGI=y
CONFIG_LIB_LIBLDAP=y
CONFIG_LIB_KRB5=y
# CONFIG_LIB_LIBLZMA is not set
CONFIG_LIB_LIBLZO=y
CONFIG_LIB_NCURSES=y
# CONFIG_LIB_LIBNET is not set
# CONFIG_LIB_LIBNET1 is not set
# CONFIG_LIB_LIBNETOLD is not set
CONFIG_LIB_LIBPAM=y
CONFIG_USER_PAM_LDAP=y
CONFIG_USER_PAM_RADIUS=y
# CONFIG_USER_PAM_SMB is not set
CONFIG_USER_PAM_KRB5=y
CONFIG_USER_PAM_TACACS=y
CONFIG_USER_PAM_ADDUSER=y
CONFIG_LIB_LIBPCAP=y
CONFIG_LIB_LIBPCRE=y
CONFIG_LIB_LIBMCRYPT=y
CONFIG_USER_NETSNMP_LIBNETSNMP=y
CONFIG_LIB_ZLIB=y
CONFIG_LIB_LIBBZ2=y
# CONFIG_LIB_LIBATM is not set
CONFIG_LIB_LIBPNG=y
# CONFIG_LIB_LIBJPEG is not set
CONFIG_LIB_LIBGD=y
# CONFIG_LIB_LIBUPNP is not set
CONFIG_LIB_LIBUSB=y
CONFIG_LIB_LIBSYSFS=y
CONFIG_LIB_NEON=y
# CONFIG_LIB_TERMCAP is not set
# CONFIG_LIB_LIBEFENCE is not set
CONFIG_LIB_STLPORT=y
CONFIG_LIB_STLPORT_SHARED=y
CONFIG_LIB_EXPAT=y
CONFIG_LIB_LIBDNSRES=y
CONFIG_LIB_LIBEVENT=y
CONFIG_LIB_SCEW=y
CONFIG_LIB_SIERRA=y
CONFIG_LIB_GOBI=y
CONFIG_LIB_LOKI=y
CONFIG_LIB_LOG4C=y
CONFIG_LIB_LIBOPENGEAR=y
# CONFIG_LIB_LIBICONV is not set
# CONFIG_LIB_FREERADIUS is not set
# CONFIG_LIB_OPENLDAP is not set
# CONFIG_LIB_ADNS is not set
# CONFIG_LIB_ARES is not set
CONFIG_LIB_LIBIDN=y
CONFIG_LIB_LIBNL=y
# CONFIG_LIB_LIBNL_COMPONENTS is not set
# CONFIG_LIB_NFNETLINK is not set
# CONFIG_LIB_NETFILTER_CONNTRACK is not set
# CONFIG_LIB_NETFILTER_LOG is not set
CONFIG_LIB_LIBIPTC=y
# CONFIG_LIB_OSIP2 is not set
# CONFIG_LIB_LIBCRYPT_OLD is not set
# CONFIG_LIB_PWLIB is not set
# CONFIG_LIB_LIBOPENH323 is not set
# CONFIG_LIB_LIBJUDY is not set
# CONFIG_LIB_CLASSPATH is not set
CONFIG_LIB_LIBFFI=y
# CONFIG_LIB_LIBXML2 is not set

#
# Library Configuration
#
CONFIG_LIB_UC_LIBC_TIMEZONE=y
CONFIG_LIB_UC_LIBC_TZ_FROM_FILE=y

#
# Firmware
#
CONFIG_LIB_FIRMWARE=y

#
# Automake Libraries
#
CONFIG_LIB_DBUS_GLIB=y
CONFIG_LIB_DBUS=y
# CONFIG_LIB_DMALLOC is not set
# CONFIG_LIB_FCGI is not set
CONFIG_LIB_GETTEXT=y
# CONFIG_LIB_GETTEXT_TOOLS is not set
CONFIG_LIB_GLIB=y
# CONFIG_LIB_GLIB_STATIC is not set
# CONFIG_LIB_GLIB_TOOLS is not set
CONFIG_LIB_JANSSON=y
CONFIG_LIB_LIBLS=y
CONFIG_LIB_LIBQMI=y
# CONFIG_LIB_LIBQMI_QMICLI is not set
# CONFIG_LIB_LIBQMI_QMI_NETWORK is not set
CONFIG_LIB_LIBSSH2=y
CONFIG_LIB_LIBUSB_1_0=y
# CONFIG_LIB_LIBUSB_COMPAT is not set
# CONFIG_LIB_LUA_COSMO is not set
# CONFIG_LIB_LUA_FS is not set
# CONFIG_LIB_LUA_JSON is not set
# CONFIG_LIB_LUA_LPEG is not set
# CONFIG_LIB_LUA_ORBIT is not set
CONFIG_LIB_LUA_POSIX=y
# CONFIG_LIB_LUA_RINGS is not set
# CONFIG_LIB_LUA_WSAPI is not set
CONFIG_LIB_MINI_ICONV=y
# CONFIG_LIB_NSPR is not set
CONFIG_LIB_SIERRA_LTE=y

#
# OpenGear Apps
#
# CONFIG_PROP_CGI_RECOVERY is not set
CONFIG_PROP_CGI_CGI=y
CONFIG_PROP_CONFIG_CONFIG=y
CONFIG_PROP_TZ_TZ=y
# CONFIG_PROP_VINO_VINO is not set
CONFIG_PROP_MOUNT_MGR=y
# CONFIG_PROP_MULTICALL is not set
CONFIG_PROP_PORTMANAGER_PORTMANAGER=y
CONFIG_PROP_PHYMASTER_PHYMASTER=y
# CONFIG_PROP_PHYMASTER_RTL8309 is not set
# CONFIG_PROP_PHYMASTER_KSZ8895 is not set
CONFIG_PROP_PORTMANAGER_PMDUMPD=y
CONFIG_PROP_PORTMANAGER_PMHOSTS=y
CONFIG_PROP_PSMON=y
CONFIG_PROP_LOOPBACK_LOOPBACK=y
# CONFIG_PROP_SETMAC_SETMAC is not set
CONFIG_PROP_INFOD_INFOD=y
CONFIG_PROP_LOGD_LOGD=y
CONFIG_PROP_CONMAN_CONMAN=y
CONFIG_PROP_ARD_ARD=y
CONFIG_PROP_RS232_RS232=y
# CONFIG_PROP_SIERRA_SIERRA is not set
CONFIG_PROP_SDT_SDT=y
CONFIG_PROP_SUPPORTREPORT_SUPPORTREPORT=y
# CONFIG_PROP_SWMON_SWMON is not set
# CONFIG_PROP_SWTCH_SWTCH is not set
# CONFIG_PROP_SWTOOL_KS8695 is not set
# CONFIG_PROP_UCD is not set
# CONFIG_PROP_CMS is not set
CONFIG_PROP_NAGIOS=y
# CONFIG_PROP_NODE_COMMAND is not set
CONFIG_PROP_LH5_NODE=y
# CONFIG_PROP_IFPROBE is not set
CONFIG_PROP_UDPGW_UDPGW=y
CONFIG_PROP_DEVLOG_DEVLOG=y
CONFIG_PROP_EMD_EMD=y
CONFIG_PROP_EMD_EXTERNAL=y
# CONFIG_PROP_EMD_KS8692 is not set
CONFIG_PROP_EMD_SYSFS=y
CONFIG_PROP_BAYTECH_BAYTECH=y
# CONFIG_PROP_MONITOR_MONITOR is not set
# CONFIG_PROP_OPENGEAR_SERIAL_CLIENT is not set
# CONFIG_PROP_POWERALERT is not set
# CONFIG_PROP_IMNITOOL is not set
# CONFIG_PROP_ULED is not set
# CONFIG_PROP_FRAM is not set
# CONFIG_PROP_ALTSW is not set
CONFIG_PROP_ALERTD=y
# CONFIG_PROP_SNMPALERTD_SNMPALERTD is not set
CONFIG_PROP_SNMPSTATUSD_SNMPSTATUSD=y
CONFIG_PROP_CELLCTL_CELLCTL=y
CONFIG_PROP_CDMASMSD=y
CONFIG_PROP_SMSD=y
CONFIG_PROP_LEDMON=y
# CONFIG_PROP_CELLRADIO is not set
CONFIG_PROP_LEDMON=y
CONFIG_PROP_SFPUTIL=y
# CONFIG_PROP_LTC3350UTIL is not set
# CONFIG_PROP_LCDUTIL is not set
# CONFIG_PROP_SHIM is not set
# CONFIG_PROP_IOC is not set
CONFIG_PROP_RPCD=y
CONFIG_PROP_SEC_LITE_SEC_LITE=y
CONFIG_PROP_URSH_URSH=y
# CONFIG_PROP_DIALMONITOR is not set

#
# OpenGear Libs
#
# CONFIG_PROP_LIBEG is not set

#
# Devmon Config
#
# CONFIG_PROP_DEVMON is not set

#
# Core Applications
#
CONFIG_USER_INIT_INIT=y
# CONFIG_USER_INIT_CONSOLE_SH is not set
# CONFIG_USER_INIT_RUN_FIREWALL is not set
# CONFIG_USER_INIT_CONF is not set
# CONFIG_USER_INIT_DISABLE_CONFIGRC is not set
# CONFIG_USER_SASH_SH is not set
# CONFIG_USER_SH_SH is not set
# CONFIG_USER_NWSH_SH is not set
CONFIG_USER_BASH_BASH=y
# CONFIG_USER_DASH_DASH is not set
# CONFIG_USER_MSH_SH is not set
# CONFIG_USER_OTHER_SH is not set
# CONFIG_USER_SASH_REBOOT is not set
# CONFIG_USER_SASH_SHUTDOWN is not set
# CONFIG_USER_INIT_EXPAND is not set
# CONFIG_USER_VERSION_VERSION is not set
CONFIG_USER_LOGIN_LOGIN=y
# CONFIG_USER_OLD_PASSWORDS is not set
# CONFIG_USER_ONLY_ROOT is not set
CONFIG_USER_AGETTY_AGETTY=y
CONFIG_USER_MGETTY_MGETTY=y
# CONFIG_USER_GETTYD_GETTYD is not set
# CONFIG_USER_LOGIN_PASSWD is not set
CONFIG_USER_SREDIRD_SREDIRD=y
# CONFIG_USER_CONSERVER_CONSERVER is not set
# CONFIG_USER_CONSOLE_CONSOLE is not set
# CONFIG_USER_CRON_CRON is not set

#
# Real Time Clock
#
CONFIG_USER_HWCLOCK_HWCLOCK=y
# CONFIG_USER_RTC_M41T11 is not set
# CONFIG_USER_RTC_DS1302 is not set

#
# USB Root Hub Controller
#
# CONFIG_USER_USBHUBCTRL_USBHUBCTRL is not set

#
# Vixie-cron
#
# CONFIG_USER_VIXIECRON_CRON is not set
# CONFIG_USER_VIXIECRON_CRONTAB is not set

#
# at
#
# CONFIG_USER_AT_AT is not set
# CONFIG_USER_AT_ATD is not set
# CONFIG_USER_AT_ATRUN is not set
# CONFIG_USER_LSOF_LSOF is not set

#
# OOM killer tinkering
#
# CONFIG_USER_NOOOM_NOOOM is not set

#
# Flash Tools
#
CONFIG_USER_FLASHW_FLASHW=y
CONFIG_USER_SETFSET_SETFSET=y
# CONFIG_USER_SETMAC_SETMAC is not set
# CONFIG_USER_FCONFIG_FCONFIG is not set

#
# netflash tool
#
CONFIG_USER_NETFLASH_NETFLASH=y
CONFIG_USER_NETFLASH_WITH_FTP=y
CONFIG_USER_NETFLASH_WITH_CGI=y
# CONFIG_USER_NETFLASH_WITH_FILE is not set
CONFIG_USER_NETFLASH_VERSION=y
# CONFIG_USER_NETFLASH_VERSION_ALLOW_CURRENT is not set
# CONFIG_USER_NETFLASH_VERSION_ALLOW_OLDER is not set
CONFIG_USER_NETFLASH_DECOMPRESS=y
# CONFIG_USER_NETFLASH_AUTODECOMPRESS is not set
# CONFIG_USER_NETFLASH_HMACMD5 is not set
# CONFIG_USER_NETFLASH_SHA256 is not set
# CONFIG_USER_NETFLASH_WITH_LCD is not set
CONFIG_USER_NETFLASH_WITH_SYSFS_LEDS=y
# CONFIG_USER_RECOVER_BIOS is not set
# CONFIG_USER_NETFLASH_CRYPTO is not set
# CONFIG_USER_NETFLASH_CRYPTO_V2 is not set
# CONFIG_USER_RECOVER_STATIC_TFTP is not set
# CONFIG_USER_RECOVER_RECOVER is not set
# CONFIG_USER_RECOVER_USE_STATIC_SERVER is not set

#
# Arcturus uCbootloader Apps/Libs
#
# CONFIG_USER_BOOTTOOLS_LOADER is not set
# CONFIG_USER_BOOTTOOLS_HIMEMLOADER is not set
# CONFIG_USER_BOOTTOOLS_PRINTBENV is not set
# CONFIG_USER_BOOTTOOLS_SETBENV is not set
# CONFIG_USER_BOOTTOOLS_RESET is not set
# CONFIG_USER_BOOTTOOLS_MD5SUM is not set
# CONFIG_LIB_LIBBSC is not set

#
# Filesystem Applications
#
CONFIG_USER_BUTTOND_BUTTOND=y
CONFIG_USER_FLATFSD_FLATFSD=y
# CONFIG_USER_FLATFSD_AUTO is not set
CONFIG_USER_FLATFSD_USE_FLASH_FS=y
# CONFIG_USER_FLATFSD_DISKLIKE is not set
# CONFIG_USER_FLATFSD_CONFIG_BLOBS is not set
# CONFIG_USER_FLATFSD_COMPRESSED is not set
# CONFIG_USER_FLATFSD_HAS_RTC is not set
# CONFIG_USER_FLATFSD_EXTERNAL_INIT is not set
# CONFIG_USER_MOUNT_MOUNT is not set
# CONFIG_USER_MOUNT_UMOUNT is not set
CONFIG_USER_FDISK_FDISK=y
CONFIG_USER_FDISK_SFDISK=y

#
# EXT2
#
CONFIG_USER_E2FSPROGS_E2FSCK_E2FSCK=y
CONFIG_USER_E2FSPROGS_MISC_MKE2FS=y
# CONFIG_USER_E2FSPROGS_MISC_BADBLOCKS is not set
# CONFIG_USER_E2FSPROGS_MISC_CHATTR is not set
# CONFIG_USER_E2FSPROGS_MISC_DUMPE2FS is not set
# CONFIG_USER_E2FSPROGS_MISC_E2LABEL is not set
# CONFIG_USER_E2FSPROGS_MISC_FSCK is not set
# CONFIG_USER_E2FSPROGS_MISC_LSATTR is not set
# CONFIG_USER_E2FSPROGS_MISC_MKLOST_FOUND is not set
# CONFIG_USER_E2FSPROGS_MISC_TUNE2FS is not set
# CONFIG_USER_E2FSPROGS_MISC_UUIDGEN is not set

#
# RESIERFS
#
# CONFIG_USER_REISERFSPROGS is not set
# CONFIG_USER_REISERFSPROGS_DEBUGRESIERFS is not set
# CONFIG_USER_REISERFSPROGS_MKREISERFS is not set
# CONFIG_USER_REISERFSPROGS_REISERFSCK is not set
# CONFIG_USER_REISERFSPROGS_RESIZE_REISERFS is not set
# CONFIG_USER_REISERFSPROGS_UNPACK is not set

#
# SAMBA
#
CONFIG_USER_SAMBA=y
# CONFIG_USER_SAMBA_SMBD is not set
# CONFIG_USER_SAMBA_NMBD is not set
CONFIG_USER_SAMBA_SMBMOUNT=y
CONFIG_USER_SAMBA_SMBUMOUNT=y
# CONFIG_USER_SAMBA_MOUNT_CIFS is not set
# CONFIG_USER_SAMBA_UMOUNT_CIFS is not set
# CONFIG_USER_SAMBA_SHARED is not set

#
# SMBFS
#
# CONFIG_USER_SMBMOUNT_SMBMOUNT is not set
# CONFIG_USER_SMBMOUNT_SMBUMOUNT is not set

#
# CRAMFS
#
# CONFIG_USER_CRAMFS_CRAMFSCK is not set
# CONFIG_USER_CRAMFS_MKCRAMFS is not set

#
# MSDOS
#
CONFIG_USER_DOSFSTOOLS_MKDOSFS=y
CONFIG_USER_DOSFSTOOLS_DOSFSCK=y
# CONFIG_USER_DOSFSTOOLS_DOSFSLABEL is not set
CONFIG_USER_MTOOLS_MTOOLS=y

#
# SquashFS
#
# CONFIG_USER_SQUASHFS_MKSQUASHFS is not set
# CONFIG_USER_SQUASHFS_MKSQUASHFS7Z is not set

#
# Network Applications
#
# CONFIG_USER_APPWEB_APPWEB is not set
# CONFIG_USER_ASTERISK is not set
# CONFIG_USER_TRUSTEDSOURCE is not set
# CONFIG_USER_BIND_BIND is not set
CONFIG_USER_CHEROKEE=y
# CONFIG_USER_FNORD_HTTPD is not set
# CONFIG_USER_FNORD_PAM is not set
# CONFIG_USER_BOA_SRC_BOA is not set
# CONFIG_USER_BPALOGIN_BPALOGIN is not set
# CONFIG_USER_BR2684CTL_BR2684CTL is not set
# CONFIG_USER_BRCFG_BRCFG is not set
CONFIG_USER_BRCTL_BRCTL=y
# CONFIG_USER_CLAMAV_CLAMAV is not set
# CONFIG_USER_CONNTRACK_CONNTRACK is not set
# CONFIG_USER_CTORRENT_CTORRENT is not set
CONFIG_USER_CURL=y
CONFIG_USER_CURL_CURL=y
CONFIG_USER_CURL_LIBCURL=y
# CONFIG_USER_DHCPCD_DHCPCD is not set
# CONFIG_USER_DHCPCD_NEW_DHCPCD is not set
# CONFIG_USER_DHCPD_DHCPD is not set
CONFIG_USER_DHCP_ISC_SERVER_DHCPD=y
# CONFIG_USER_DHCP_ISC_CLIENT_DHCLIENT is not set
# CONFIG_USER_DHCP_ISC_RELAY_DHCRELAY is not set
# CONFIG_USER_DIALD_DIALD is not set
CONFIG_USER_DISCARD_DISCARD=y
CONFIG_USER_DISCARD_NO_INSTALL=y
CONFIG_USER_DISCARD_INETD_ECHO=y
CONFIG_USER_DISCARD_ECHO_NO_INSTALL=y
CONFIG_USER_DNSMASQ_DNSMASQ=y
CONFIG_USER_DNSMASQ2_DNSMASQ2=y
# CONFIG_USER_DROPBEAR_DROPBEAR is not set
# CONFIG_USER_ETHATTACH_ETHATTACH is not set
# CONFIG_USER_ETHERWAKE is not set
CONFIG_USER_ETHTOOL_ETHTOOL=y
CONFIG_USER_EZIPUPDATE_EZIPUPDATE=y
# CONFIG_USER_FAKEIDENTD_IDENTD is not set
# CONFIG_USER_DDNS3_CLIENT_DDNS3 is not set
# CONFIG_USER_FERRET_FERRET is not set
CONFIG_USER_FTP_FTP_FTP=y
CONFIG_USER_FTPD_FTPD=y
# CONFIG_USER_FROX_FROX is not set
# CONFIG_USER_FREESWAN is not set
CONFIG_USER_OPENSWAN=y
CONFIG_USER_OPENSWAN_PLUTO_PLUTO=y
CONFIG_USER_OPENSWAN_PLUTO_WHACK=y
CONFIG_USER_OPENSWAN_UTILS_RANBITS=y
CONFIG_USER_OPENSWAN_UTILS_RSASIGKEY=y
CONFIG_USER_OPENSWAN_KLIPS_EROUTE=y
CONFIG_USER_OPENSWAN_KLIPS_KLIPSDEBUG=y
CONFIG_USER_OPENSWAN_KLIPS_SPI=y
CONFIG_USER_OPENSWAN_KLIPS_SPIGRP=y
CONFIG_USER_OPENSWAN_KLIPS_TNCFG=y
CONFIG_USER_OPENSWAN_PROGRAMS_LWDNSQ=y
# CONFIG_IPSEC_CONNECTION_LIMIT_BOOL is not set
# CONFIG_USER_GNUGK_GNUGK is not set
# CONFIG_USER_HPING_HPING is not set
# CONFIG_USER_HTTPD_HTTPD is not set
# CONFIG_USER_HTTPTUNNEL_CLIENT is not set
# CONFIG_USER_HTTPTUNNEL_SERVER is not set
# CONFIG_USER_IFATTACH_IFATTACH is not set
CONFIG_USER_INETD_INETD=y
# CONFIG_USER_IPCHAINS_IPCHAINS is not set
CONFIG_USER_IFENSLAVE_IFENSLAVE=y
# CONFIG_USER_IPERF_IPERF is not set
# CONFIG_USER_IPFWADM_IPFWADM is not set
# CONFIG_USER_IPMASQADM_IPMASQADM is not set
CONFIG_USER_IPMITOOL_IPMITOOL=y
# CONFIG_USER_IPMITOOL_IPMIEVD is not set
# CONFIG_USER_IPMITOOL_IPMISHELL is not set
# CONFIG_USER_IPPORTFW_IPPORTFW is not set
# CONFIG_USER_IPREDIR_IPREDIR is not set
CONFIG_USER_IPROUTE2=y
CONFIG_USER_IPROUTE2_TC_TC=y
# CONFIG_USER_IPROUTE2_IP_IFCFG is not set
CONFIG_USER_IPROUTE2_IP_IP=y
CONFIG_USER_IPROUTE2_IP_ROUTEF=y
CONFIG_USER_IPROUTE2_IP_ROUTEL=y
CONFIG_USER_IPROUTE2_IP_RTACCT=y
CONFIG_USER_IPROUTE2_IP_RTMON=y
# CONFIG_USER_IPROUTE2_IP_RTPR is not set
# CONFIG_USER_IPSENTINEL_IPSENTINEL is not set
# CONFIG_USER_IPSET_IPSET is not set
CONFIG_USER_IPSETD_IPSETD=y
CONFIG_USER_IPTABLES_IPTABLES=y
# CONFIG_USER_LAYER7_PROTOCOLS is not set
CONFIG_USER_IPTABLES_IP6TABLES=y
# CONFIG_USER_IPWATCHD_IPWATCHD is not set
CONFIG_USER_IPUTILS_IPUTILS=y
CONFIG_USER_IPUTILS_PING=y
CONFIG_USER_IPUTILS_PING6=y
CONFIG_USER_IPUTILS_TRACEROUTE6=y
# CONFIG_USER_IPUTILS_RDISC is not set
# CONFIG_USER_IPUTILS_CLOCKDIFF is not set
# CONFIG_USER_IPUTILS_TFTPD is not set
# CONFIG_USER_IPUTILS_TRACEPATH is not set
# CONFIG_USER_IPUTILS_TRACEPATH6 is not set
# CONFIG_USER_IPUTILS_ARPING is not set
# CONFIG_USER_IPUTILS_RARPD is not set
# CONFIG_USER_KENDIN_KSCLI is not set
# CONFIG_USER_KENDIN_CONFIG is not set
# CONFIG_USER_KLAXON_KLAXON is not set
# CONFIG_USER_L2TPD_L2TPD is not set
# CONFIG_USER_LINUXIGD_LINUXIGD is not set
# CONFIG_USER_MINIUPNPD is not set
# CONFIG_USER_LOATTACH_LOATTACH is not set
# CONFIG_USER_LRPSTAT_LRPSTAT is not set
CONFIG_USER_SMTP_SMTPCLIENT=y
# CONFIG_USER_MAIL_MAIL_IP is not set
# CONFIG_USER_MARADNS_MARADNS is not set
# CONFIG_USER_MINI_HTTPD_MINI_HTTPD is not set
# CONFIG_USER_MSNTP_MSNTP is not set
# CONFIG_USER_NESSUS is not set
# CONFIG_USER_NESSUS_NASL is not set
# CONFIG_USER_NESSUS_CORE is not set
# CONFIG_USER_NESSUS_PLUGINS is not set
# CONFIG_USER_NESSUS_LIBRARIES is not set
CONFIG_USER_NETCAT_NETCAT=y
# CONFIG_USER_NETPERF_NETPERF is not set
# CONFIG_USER_NETPERF_NETSERVER is not set
# CONFIG_USER_NETPIPE_NETPIPE is not set
# CONFIG_USER_NETSTAT_NAT_NETSTAT_NAT is not set
CONFIG_USER_NETSNMP_SNMPD=y
# CONFIG_USER_NETSNMP_NETSNMP_52 is not set
# CONFIG_USER_NETSNMP_SNMPD_MINI is not set
CONFIG_USER_NETSNMP_APPS=y
# CONFIG_USER_NETSNMP_APPS_BULKGET is not set
# CONFIG_USER_NETSNMP_APPS_BULKWALK is not set
# CONFIG_USER_NETSNMP_APPS_DELTA is not set
# CONFIG_USER_NETSNMP_APPS_DF is not set
CONFIG_USER_NETSNMP_APPS_GET=y
# CONFIG_USER_NETSNMP_APPS_GETNEXT is not set
CONFIG_USER_NETSNMP_APPS_SET=y
# CONFIG_USER_NETSNMP_APPS_STATUS is not set
# CONFIG_USER_NETSNMP_APPS_TABLE is not set
# CONFIG_USER_NETSNMP_APPS_TEST is not set
# CONFIG_USER_NETSNMP_APPS_TRANSLATE is not set
CONFIG_USER_NETSNMP_APPS_TRAP=y
CONFIG_USER_NETSNMP_APPS_TRAPD=y
# CONFIG_USER_NETSNMP_APPS_USM is not set
# CONFIG_USER_NETSNMP_APPS_VACM is not set
CONFIG_USER_NETSNMP_APPS_WALK=y
# CONFIG_USER_NETSNMP_APPS_NETSTAT is not set
# CONFIG_USER_NETSNMP_BUILDSTATIC is not set
CONFIG_USER_NETSNMP_BUILDSHARED=y
# CONFIG_USER_NETSNMP_MANUALS is not set
# CONFIG_USER_NETSNMP_SCRIPTS is not set
# CONFIG_USER_NETSNMP_MIBS is not set
CONFIG_USER_NETSNMP_MIBLOADING=y
# CONFIG_USER_NETSNMP_NOV1 is not set
# CONFIG_USER_NETSNMP_NOV2C is not set
# CONFIG_USER_NETSNMP_IPV6 is not set
# CONFIG_USER_NETSNMP_NOTRANSPORTS is not set
# CONFIG_USER_NETSNMP_OPENSSL is not set
# CONFIG_USER_NETSNMP_OVRDEFAULTS is not set
# CONFIG_USER_NETSNMP_ADDMIBS is not set
CONFIG_USER_NETSNMP_AGENT_SNMPD=y
CONFIG_USER_NUT=y
CONFIG_USER_NUT_WITH_SNMP=y
CONFIG_USER_NUT_WITH_XML=y
CONFIG_USER_NUT_WITH_OTHERS=y
# CONFIG_USER_MARADNS_ZONESERVER is not set
# CONFIG_USER_NMAP_NMAP is not set
# CONFIG_USER_NTPCLIENT_NTPCLIENT is not set
# CONFIG_USER_NTPCLIENT_ADJTIMEX is not set
CONFIG_USER_NTPD_NTPD=y
# CONFIG_USER_NTPD_NTPDC is not set
# CONFIG_USER_NTPD_NTPDATE is not set
CONFIG_USER_NTPD_NTPQ=y
# CONFIG_USER_OPENNTPD_OPENNTPD is not set
# CONFIG_USER_OPENRRCP_RTL8326 is not set
CONFIG_USER_OPENSSL_APPS=y
CONFIG_USER_OPENVPN_OPENVPN=y
# CONFIG_USER_SSCEP is not set
# CONFIG_USER_PING_PING is not set
# CONFIG_USER_PLUG_PLUG is not set
# CONFIG_USER_POP3PROXY_POP3PROXY is not set
CONFIG_USER_PORTMAP_PORTMAP=y
# CONFIG_USER_PORTMAP_PMAP_SET is not set
# CONFIG_USER_PORTMAP_PMAP_DUMP is not set
CONFIG_USER_PPPD_PPPD_PPPD=y
# CONFIG_USER_PPPD_WITH_DYNAMIC_PLUGINS is not set
# CONFIG_USER_PPPD_WITH_IPV6 is not set
# CONFIG_USER_PPPD_WITH_PAM is not set
CONFIG_USER_PPPD_WITH_MPPE=y
# CONFIG_USER_PPPD_WITH_TACACS is not set
# CONFIG_USER_PPPD_WITH_RADIUS is not set
# CONFIG_USER_PPPD_WITH_PPPOE is not set
# CONFIG_USER_PPPD_WITH_PPPOA is not set
CONFIG_USER_PPPD_NO_AT_REDIRECTION=y
# CONFIG_USER_PPPD_WITH_MINCONN is not set
# CONFIG_USER_PPPD_WITH_PASSPROMPT is not set
# CONFIG_USER_PPPD_WITH_PASSWORDFD is not set
# CONFIG_USER_PPPD_WITH_WINBIND is not set
CONFIG_USER_PPTPD_PPTPCTRL=y
CONFIG_USER_PPTPD_PPTPD=y
# CONFIG_USER_PPTP_PPTP is not set
# CONFIG_USER_PPTP_CLIENT_PPTP is not set
# CONFIG_USER_PPTP_CLIENT_PPTP_CALLMGR is not set
# CONFIG_USER_PROFTPD_PROFTPD is not set
CONFIG_USER_QUAGGA_ZEBRA_ZEBRA=y
# CONFIG_USER_QUAGGA_BGPD_BGPD is not set
CONFIG_USER_QUAGGA_OSPFD_OSPFD=y
# CONFIG_USER_QUAGGA_OSPF6D_OSPF6D is not set
CONFIG_USER_QUAGGA_RIPD_RIPD=y
# CONFIG_USER_QUAGGA_RIPNGD_RIPNGD is not set
# CONFIG_USER_QUAGGA_WATCHQUAGGA_WATCHQUAGGA is not set
CONFIG_USER_QUAGGA_VTYSH_VTYSH=y
# CONFIG_USER_RADVD_RADVD is not set
# CONFIG_USER_RADAUTH_RADAUTH is not set
# CONFIG_USER_RDATE_RDATE is not set
# CONFIG_USER_ROUTED_ROUTED is not set
# CONFIG_USER_RP_PPPOE_PPPOE is not set
# CONFIG_USER_RSYNC_RSYNC is not set
# CONFIG_USER_RSYSLOG_RSYSLOGD is not set
# CONFIG_USER_RSYSLOGD_RSYSLOGD is not set
# CONFIG_USER_LOGROTATE_LOGROTATE is not set
# CONFIG_USER_SENDIP_SENDIP is not set
# CONFIG_USER_SER_SER is not set
# CONFIG_USER_SETHDLC_SETHDLC is not set
# CONFIG_USER_SIPROXD_SIPROXD is not set
# CONFIG_USER_SLATTACH_SLATTACH is not set
# CONFIG_USER_SMSTOOLS3 is not set
# CONFIG_USER_SNMPD_SNMPD is not set
# CONFIG_USER_SNORT_SNORT is not set
# CONFIG_USER_SPEEDTOUCH_MODEM_RUN is not set
CONFIG_USER_STUNNEL_STUNNEL=y
# CONFIG_USER_SSLWRAP_SSLWRAP is not set
# CONFIG_USER_SQUID_SQUID is not set
# CONFIG_USER_STP_STP is not set
# CONFIG_USER_TCPWRAP_TCPD is not set
# CONFIG_USER_TCPBLAST_TCPBLAST is not set
CONFIG_USER_TCPDUMP_TCPDUMP=y
CONFIG_USER_TELNETD_TELNETD=y
# CONFIG_USER_TELNETD_DOES_NOT_USE_OPENPTY is not set
# CONFIG_USER_TELNET_TELNET is not set
CONFIG_USER_TFTP_TFTP=y
# CONFIG_USER_TFTPD_TFTPD is not set
# CONFIG_USER_THTTPD_THTTPD is not set
# CONFIG_USER_TINYPROXY_TINYPROXY is not set
CONFIG_USER_UDEV=y
# CONFIG_USER_ULOGD_ULOGD is not set
# CONFIG_USER_ULOGD2_ULOGD is not set
CONFIG_USER_VCONFIG_VCONFIG=y
# CONFIG_USER_VPNLED_VPNLED is not set
# CONFIG_USER_WGET is not set
# CONFIG_USER_ZEBRA_ZEBRA_ZEBRA is not set

#
# Net-tools
#
CONFIG_USER_NET_TOOLS_ARP=y
# CONFIG_USER_NET_TOOLS_HOSTNAME is not set
CONFIG_USER_NET_TOOLS_IFCONFIG=y
# CONFIG_USER_NET_TOOLS_NAMEIF is not set
CONFIG_USER_NET_TOOLS_NETSTAT=y
# CONFIG_USER_NET_TOOLS_PLIPCONFIG is not set
# CONFIG_USER_NET_TOOLS_RARP is not set
CONFIG_USER_NET_TOOLS_ROUTE=y
# CONFIG_USER_NET_TOOLS_SLATTACH is not set
CONFIG_USER_NET_TOOLS_MII_TOOL=y
# CONFIG_USER_NET_TOOLS_MII_TOOL_FEC is not set

#
# Wireless-tools
#
# CONFIG_USER_WIRELESS_TOOLS is not set
# CONFIG_USER_WPA_SUPPLICANT is not set
# CONFIG_USER_HOSTAPD is not set
# CONFIG_USER_WLAN_NG is not set

#
# Miscellaneous Applications
#
# CONFIG_USER_P7ZIP_7ZA is not set
# CONFIG_USER_LANG_A60 is not set
# CONFIG_USER_ARJ_ARJ is not set
# CONFIG_USER_AUTOBUILD is not set
# CONFIG_USER_BZIP2_BZIP2 is not set
# CONFIG_USER_CAL_CAL is not set
# CONFIG_USER_CAN_EXAMPLES is not set
CONFIG_USER_CHAT_CHAT=y
# CONFIG_USER_CHAT_CHAT_NETWORK is not set
# CONFIG_USER_CKSUM_CKSUM is not set
# CONFIG_USER_CLOCK_CLOCK is not set
# CONFIG_USER_CPU_CPU is not set
# CONFIG_USER_CRYPTO_TOOLS_CRYPTOTEST is not set
# CONFIG_USER_CRYPTO_TOOLS_CRYPTOKEYTEST is not set
# CONFIG_USER_CAL_DATE is not set
# CONFIG_USER_DE2TSCAL_DE2TSCAL is not set
# CONFIG_USER_DEVMEM2_DEVMEM2 is not set
# CONFIG_USER_EXPAT_EXAMPLES is not set
# CONFIG_USER_EXPECT_EXPECT is not set
# CONFIG_USER_TCL_LIBTCL is not set
# CONFIG_USER_FLTHDR_FLTHDR is not set
# CONFIG_USER_FROB_LED_FROB_LED is not set
# CONFIG_USER_GDB_GDBREPLAY is not set
# CONFIG_USER_GDB_GDBSERVER is not set
# CONFIG_USER_GDB_TARGET is not set
# CONFIG_USER_GDB_HOST is not set
# CONFIG_USER_GDBSERVER_GDBREPLAY is not set
# CONFIG_USER_GDBSERVER_GDBSERVER is not set
# CONFIG_USER_DEBUG_DEBUG is not set
# CONFIG_USER_GREP_GREP is not set
# CONFIG_USER_HASERL_HASERL is not set
CONFIG_USER_HD_HD=y
# CONFIG_USER_CAN_HORCH is not set
# CONFIG_USER_JAMVM_JAMVM is not set
# CONFIG_USER_KEXEC_KEXEC is not set
# CONFIG_USER_SGUTOOL_SGUTOOL is not set
# CONFIG_USER_LCD_LCD is not set
# CONFIG_USER_LEDCON_LEDCON is not set
# CONFIG_USER_LHA_LHA is not set
# CONFIG_USER_LILO_LILO is not set
# CONFIG_USER_LISSA_LISSA is not set
# CONFIG_USER_LPR is not set
# CONFIG_USER_LUA_LUA is not set
# CONFIG_USER_USBCBI_USBCBI is not set
# CONFIG_USER_USBISO_USBISO is not set
# CONFIG_USER_MATH_TEST is not set
# CONFIG_USER_MAWK_AWK is not set
# CONFIG_USER_MYSQL is not set
CONFIG_USER_NAGIOS_PLUGINS=y
CONFIG_USER_NRPE=y
CONFIG_USER_NSCA=y
# CONFIG_USER_NULL_NULL is not set
# CONFIG_USER_OPROFILE is not set
# CONFIG_USER_PALMBOT_PALMBOT is not set
# CONFIG_USER_PCMCIA_CS is not set
# CONFIG_USER_PERL_PERL is not set
CONFIG_USER_POWERMAN_POWERMAN=y
# CONFIG_USER_POTRACE_POTRACE is not set
# CONFIG_USER_PYTHON_PYTHON is not set
# CONFIG_USER_PYTHON152_PYTHON is not set
# CONFIG_USER_READPROFILE_READPROFILE is not set
# CONFIG_USER_ROOTLOADER_ROOTLOADER is not set
# CONFIG_USER_RRDTOOL_RRDTOOL is not set
# CONFIG_USER_RUBY18_RUBY is not set
CONFIG_USER_SETSERIAL_SETSERIAL=y
# CONFIG_USER_SHADOW_UTILS is not set
# CONFIG_USER_TRIPWIRE_SIGGEN is not set
CONFIG_USER_SIGS_SIGS=y
CONFIG_USER_STRACE_STRACE=y
# CONFIG_USER_STTY_STTY is not set
# CONFIG_USER_TCSH_TCSH is not set
# CONFIG_USER_TINYTCL_TCLSH is not set
# CONFIG_LIB_TINYTCL is not set
# CONFIG_USER_THREADDEMOS_THREADDEMOS is not set
CONFIG_USER_TIP_TIP=y
# CONFIG_USER_TRIPWIRE_TRIPWIRE is not set
# CONFIG_USER_UNRAR_UNRAR is not set
# CONFIG_USER_UNZIP_UNZIP is not set
# CONFIG_USER_UNZOO_UNZOO is not set
# CONFIG_USER_WATCHDOGD is not set
CONFIG_USER_LRZSZ_LRZSZ=y
CONFIG_USER_LRZSZ_LRZ=y
CONFIG_USER_LRZSZ_LSZ=y
CONFIG_USER_ZIP_ZIP=y

#
# Benchmarks
#
# CONFIG_USER_DHRYSTONE_DHRYSTONE is not set
# CONFIG_USER_NBENCH_NBENCH is not set
# CONFIG_USER_WHETSTONE_WHETSTONE is not set

#
# LIRC
#
# CONFIG_USER_LIRC is not set

#
# LM SENSORS
#
# CONFIG_USER_LM_SENSORS is not set
CONFIG_USER_LM_SENSORS_3=y
CONFIG_USER_LM_SENSORS_3_SENSORS=y

#
# QSPI
#
# CONFIG_MCF_QSPI is not set

#
# Editors
#
# CONFIG_USER_LEVEE_VI is not set
# CONFIG_USER_ELVISTINY_VI is not set
# CONFIG_USER_NANO_NANO is not set

#
# Audio tools
#
# CONFIG_USER_MP3PLAY_MP3PLAY is not set
# CONFIG_USER_OGGPLAY_OGGPLAY is not set
# CONFIG_USER_OGGPLAY_EXAMPLE is not set
# CONFIG_USER_MUSICBOX_MUSICBOX is not set
# CONFIG_USER_PLAY_PLAY is not set
# CONFIG_USER_PLAY_TONE is not set
# CONFIG_USER_VPLAY_VPLAY is not set
# CONFIG_USER_VPLAY_VREC is not set
# CONFIG_USER_VPLAY_MIXER is not set
# CONFIG_USER_PLAYRT_PLAYRT is not set

#
# Video tools
#
# CONFIG_USER_CAMSERV is not set
# CONFIG_USER_JPEGVIEW_JPEGVIEW is not set
# CONFIG_USER_W3CAM_VIDCAT is not set
# CONFIG_USER_W3CAM_W3CAMD is not set

#
# Fileutils tools
#
# CONFIG_USER_FILEUTILS_CAT is not set
# CONFIG_USER_FILEUTILS_CHGRP is not set
# CONFIG_USER_FILEUTILS_CHMOD is not set
# CONFIG_USER_FILEUTILS_CHOWN is not set
# CONFIG_USER_FILEUTILS_CMP is not set
# CONFIG_USER_FILEUTILS_CP is not set
# CONFIG_USER_FILEUTILS_DD is not set
# CONFIG_USER_FILEUTILS_GREP is not set
# CONFIG_USER_FILEUTILS_L is not set
# CONFIG_USER_FILEUTILS_LN is not set
# CONFIG_USER_FILEUTILS_LS is not set
# CONFIG_USER_FILEUTILS_MKDIR is not set
# CONFIG_USER_FILEUTILS_MKFIFO is not set
# CONFIG_USER_FILEUTILS_MKNOD is not set
# CONFIG_USER_FILEUTILS_MORE is not set
# CONFIG_USER_FILEUTILS_MV is not set
# CONFIG_USER_FILEUTILS_RM is not set
# CONFIG_USER_FILEUTILS_RMDIR is not set
# CONFIG_USER_FILEUTILS_SYNC is not set
# CONFIG_USER_FILEUTILS_TOUCH is not set

#
# Shutils tools
#
# CONFIG_USER_SHUTILS_BASENAME is not set
# CONFIG_USER_SHUTILS_DATE is not set
# CONFIG_USER_SHUTILS_DIRNAME is not set
# CONFIG_USER_SHUTILS_ECHO is not set
# CONFIG_USER_SHUTILS_FALSE is not set
# CONFIG_USER_SHUTILS_LOGNAME is not set
# CONFIG_USER_SHUTILS_PRINTENV is not set
# CONFIG_USER_SHUTILS_PWD is not set
# CONFIG_USER_SHUTILS_TRUE is not set
# CONFIG_USER_SHUTILS_UNAME is not set
# CONFIG_USER_SHUTILS_WHICH is not set
# CONFIG_USER_SHUTILS_WHOAMI is not set
# CONFIG_USER_SHUTILS_YES is not set

#
# Sysutils tools
#
# CONFIG_USER_SYSUTILS_REBOOT is not set
# CONFIG_USER_SYSUTILS_SHUTDOWN is not set
# CONFIG_USER_SYSUTILS_DF is not set
# CONFIG_USER_SYSUTILS_FREE is not set
# CONFIG_USER_SYSUTILS_HOSTNAME is not set
# CONFIG_USER_SYSUTILS_KILL is not set
# CONFIG_USER_SYSUTILS_PS is not set

#
# Procps tools
#
# CONFIG_USER_PROCPS_FREE is not set
# CONFIG_USER_PROCPS_KILL is not set
CONFIG_USER_PROCPS_PGREP=y
CONFIG_USER_PROCPS_PKILL=y
# CONFIG_USER_PROCPS_PS is not set
# CONFIG_USER_PROCPS_SNICE is not set
CONFIG_USER_PROCPS_SYSCTL=y
# CONFIG_USER_PROCPS_TLOAD is not set
CONFIG_USER_PROCPS_TOP=y
# CONFIG_USER_PROCPS_UPTIME is not set
# CONFIG_USER_PROCPS_VMSTAT is not set
CONFIG_USER_PROCPS_W=y
# CONFIG_USER_PROCPS_WATCH is not set
# CONFIG_USER_PROCPS_PMAP is not set
# CONFIG_USER_PROCPS_SLABTOP is not set
# CONFIG_USER_PROCPS_PWDX is not set

#
# PCI utilities
#
CONFIG_USER_PCIUTILS_LSPCI=y
# CONFIG_USER_PCIUTILS_SETPCI is not set

#
# Test Applications
#
# CONFIG_USER_CXXTEST_CXXTEST is not set

#
# BusyBox
#
CONFIG_USER_BUSYBOX_BUSYBOX=y

#
# BusyBox Configuration
#
CONFIG_USER_BUSYBOX_HAVE_DOT_CONFIG=y

#
# Busybox Settings
#

#
# General Configuration
#
# CONFIG_USER_BUSYBOX_NITPICK is not set
# CONFIG_USER_BUSYBOX_DESKTOP is not set
CONFIG_USER_BUSYBOX_SHOW_USAGE=y
CONFIG_USER_BUSYBOX_FEATURE_VERBOSE_USAGE=y
CONFIG_USER_BUSYBOX_FEATURE_COMPRESS_USAGE=y
# CONFIG_USER_BUSYBOX_FEATURE_INSTALLER is not set
# CONFIG_USER_BUSYBOX_LOCALE_SUPPORT is not set
CONFIG_USER_BUSYBOX_GETOPT_LONG=y
CONFIG_USER_BUSYBOX_FEATURE_DEVPTS=y
CONFIG_USER_BUSYBOX_FEATURE_PIDFILE=y
CONFIG_USER_BUSYBOX_FEATURE_SUID=y
# CONFIG_USER_BUSYBOX_FEATURE_SUID_CONFIG is not set
# CONFIG_USER_BUSYBOX_SELINUX is not set
# CONFIG_USER_BUSYBOX_FEATURE_PREFER_APPLETS is not set
CONFIG_USER_BUSYBOX_BUSYBOX_EXEC_PATH="/proc/self/exe"
CONFIG_USER_BUSYBOX_FEATURE_SYSLOG=y
CONFIG_USER_BUSYBOX_FEATURE_HAVE_RPC=y

#
# Build Options
#
# CONFIG_USER_BUSYBOX_STATIC is not set
# CONFIG_USER_BUSYBOX_NOMMU is not set
# CONFIG_USER_BUSYBOX_BUILD_LIBBUSYBOX is not set
# CONFIG_USER_BUSYBOX_LFS is not set

#
# Debugging Options
#
# CONFIG_USER_BUSYBOX_DEBUG is not set
# CONFIG_USER_BUSYBOX_WERROR is not set
CONFIG_USER_BUSYBOX_NO_DEBUG_LIB=y
# CONFIG_USER_BUSYBOX_DMALLOC is not set
# CONFIG_USER_BUSYBOX_EFENCE is not set
CONFIG_USER_BUSYBOX_INCLUDE_SUSv2=y

#
# Installation Options
#
# CONFIG_USER_BUSYBOX_INSTALL_NO_USR is not set
CONFIG_USER_BUSYBOX_INSTALL_APPLET_SYMLINKS=y
# CONFIG_USER_BUSYBOX_INSTALL_APPLET_HARDLINKS is not set
# CONFIG_USER_BUSYBOX_INSTALL_APPLET_SCRIPT_WRAPPERS is not set
# CONFIG_USER_BUSYBOX_INSTALL_APPLET_DONT is not set
CONFIG_USER_BUSYBOX_PREFIX="./_install"

#
# Busybox Library Tuning
#
CONFIG_USER_BUSYBOX_PASSWORD_MINLEN=6
CONFIG_USER_BUSYBOX_MD5_SIZE_VS_SPEED=2
CONFIG_USER_BUSYBOX_FEATURE_FAST_TOP=y
# CONFIG_USER_BUSYBOX_FEATURE_ETC_NETWORKS is not set
# CONFIG_USER_BUSYBOX_FEATURE_EDITING is not set
CONFIG_USER_BUSYBOX_FEATURE_VERBOSE_CP_MESSAGE=y
CONFIG_USER_BUSYBOX_FEATURE_COPYBUF_KB=4
CONFIG_USER_BUSYBOX_MONOTONIC_SYSCALL=y
CONFIG_USER_BUSYBOX_IOCTL_HEX2STR_ERROR=y

#
# Applets
#

#
# Archival Utilities
#
# CONFIG_USER_BUSYBOX_AR is not set
# CONFIG_USER_BUSYBOX_BUNZIP2 is not set
# CONFIG_USER_BUSYBOX_BZIP2 is not set
# CONFIG_USER_BUSYBOX_CPIO is not set
# CONFIG_USER_BUSYBOX_DPKG is not set
# CONFIG_USER_BUSYBOX_DPKG_DEB is not set
CONFIG_USER_BUSYBOX_GUNZIP=y
# CONFIG_USER_BUSYBOX_FEATURE_GUNZIP_UNCOMPRESS is not set
CONFIG_USER_BUSYBOX_GZIP=y
# CONFIG_USER_BUSYBOX_RPM2CPIO is not set
# CONFIG_USER_BUSYBOX_RPM is not set
CONFIG_USER_BUSYBOX_TAR=y
CONFIG_USER_BUSYBOX_FEATURE_TAR_CREATE=y
CONFIG_USER_BUSYBOX_FEATURE_TAR_GZIP=y
# CONFIG_USER_BUSYBOX_FEATURE_TAR_BZIP2 is not set
# CONFIG_USER_BUSYBOX_FEATURE_TAR_LZMA is not set
# CONFIG_USER_BUSYBOX_FEATURE_TAR_COMPRESS is not set
# CONFIG_USER_BUSYBOX_FEATURE_TAR_AUTODETECT is not set
# CONFIG_USER_BUSYBOX_FEATURE_TAR_FROM is not set
# CONFIG_USER_BUSYBOX_FEATURE_TAR_OLDGNU_COMPATIBILITY is not set
# CONFIG_USER_BUSYBOX_FEATURE_TAR_OLDSUN_COMPATIBILITY is not set
CONFIG_USER_BUSYBOX_FEATURE_TAR_GNU_EXTENSIONS=y
# CONFIG_USER_BUSYBOX_FEATURE_TAR_LONG_OPTIONS is not set
# CONFIG_USER_BUSYBOX_FEATURE_TAR_UNAME_GNAME is not set
# CONFIG_USER_BUSYBOX_UNCOMPRESS is not set
# CONFIG_USER_BUSYBOX_UNLZMA is not set
# CONFIG_USER_BUSYBOX_UNZIP is not set

#
# Common options for cpio and tar
#
# CONFIG_USER_BUSYBOX_FEATURE_UNARCHIVE_TAPE is not set

#
# Coreutils
#
CONFIG_USER_BUSYBOX_BASENAME=y
# CONFIG_USER_BUSYBOX_CAL is not set
CONFIG_USER_BUSYBOX_CAT=y
# CONFIG_USER_BUSYBOX_CATV is not set
CONFIG_USER_BUSYBOX_CHGRP=y
CONFIG_USER_BUSYBOX_CHMOD=y
CONFIG_USER_BUSYBOX_CHOWN=y
# CONFIG_USER_BUSYBOX_CHROOT is not set
# CONFIG_USER_BUSYBOX_CKSUM is not set
CONFIG_USER_BUSYBOX_COMM=y
CONFIG_USER_BUSYBOX_CP=y
CONFIG_USER_BUSYBOX_CUT=y
CONFIG_USER_BUSYBOX_DATE=y
CONFIG_USER_BUSYBOX_FEATURE_DATE_ISOFMT=y
CONFIG_USER_BUSYBOX_DD=y
CONFIG_USER_BUSYBOX_FEATURE_DD_SIGNAL_HANDLING=y
CONFIG_USER_BUSYBOX_FEATURE_DD_IBS_OBS=y
CONFIG_USER_BUSYBOX_DF=y
CONFIG_USER_BUSYBOX_FEATURE_DF_INODE=y
CONFIG_USER_BUSYBOX_DIRNAME=y
CONFIG_USER_BUSYBOX_DOS2UNIX=y
CONFIG_USER_BUSYBOX_UNIX2DOS=y
CONFIG_USER_BUSYBOX_DU=y
CONFIG_USER_BUSYBOX_FEATURE_DU_DEFAULT_BLOCKSIZE_1K=y
CONFIG_USER_BUSYBOX_ECHO=y
CONFIG_USER_BUSYBOX_FEATURE_FANCY_ECHO=y
CONFIG_USER_BUSYBOX_ENV=y
# CONFIG_USER_BUSYBOX_FEATURE_ENV_LONG_OPTIONS is not set
# CONFIG_USER_BUSYBOX_EXPAND is not set
CONFIG_USER_BUSYBOX_EXPR=y
# CONFIG_USER_BUSYBOX_EXPR_MATH_SUPPORT_64 is not set
CONFIG_USER_BUSYBOX_FALSE=y
# CONFIG_USER_BUSYBOX_FOLD is not set
CONFIG_USER_BUSYBOX_HEAD=y
CONFIG_USER_BUSYBOX_FEATURE_FANCY_HEAD=y
CONFIG_USER_BUSYBOX_HOSTID=y
CONFIG_USER_BUSYBOX_ID=y
# CONFIG_USER_BUSYBOX_INSTALL is not set
# CONFIG_USER_BUSYBOX_LENGTH is not set
CONFIG_USER_BUSYBOX_LN=y
# CONFIG_USER_BUSYBOX_LOGNAME is not set
CONFIG_USER_BUSYBOX_LS=y
CONFIG_USER_BUSYBOX_FEATURE_LS_FILETYPES=y
CONFIG_USER_BUSYBOX_FEATURE_LS_FOLLOWLINKS=y
CONFIG_USER_BUSYBOX_FEATURE_LS_RECURSIVE=y
CONFIG_USER_BUSYBOX_FEATURE_LS_SORTFILES=y
CONFIG_USER_BUSYBOX_FEATURE_LS_TIMESTAMPS=y
CONFIG_USER_BUSYBOX_FEATURE_LS_USERNAME=y
CONFIG_USER_BUSYBOX_FEATURE_LS_COLOR=y
# CONFIG_USER_BUSYBOX_FEATURE_LS_COLOR_IS_DEFAULT is not set
CONFIG_USER_BUSYBOX_MD5SUM=y
CONFIG_USER_BUSYBOX_MKDIR=y
# CONFIG_USER_BUSYBOX_FEATURE_MKDIR_LONG_OPTIONS is not set
CONFIG_USER_BUSYBOX_MKFIFO=y
CONFIG_USER_BUSYBOX_MKNOD=y
CONFIG_USER_BUSYBOX_MV=y
# CONFIG_USER_BUSYBOX_FEATURE_MV_LONG_OPTIONS is not set
# CONFIG_USER_BUSYBOX_NICE is not set
CONFIG_USER_BUSYBOX_NOHUP=y
CONFIG_USER_BUSYBOX_OD=y
# CONFIG_USER_BUSYBOX_PRINTENV is not set
CONFIG_USER_BUSYBOX_PRINTF=y
CONFIG_USER_BUSYBOX_PWD=y
CONFIG_USER_BUSYBOX_READLINK=y
# CONFIG_USER_BUSYBOX_FEATURE_READLINK_FOLLOW is not set
CONFIG_USER_BUSYBOX_REALPATH=y
CONFIG_USER_BUSYBOX_RM=y
CONFIG_USER_BUSYBOX_RMDIR=y
# CONFIG_USER_BUSYBOX_FEATURE_RMDIR_LONG_OPTIONS is not set
# CONFIG_USER_BUSYBOX_SEQ is not set
CONFIG_USER_BUSYBOX_SHA1SUM=y
CONFIG_USER_BUSYBOX_SLEEP=y
CONFIG_USER_BUSYBOX_FEATURE_FANCY_SLEEP=y
CONFIG_USER_BUSYBOX_SORT=y
CONFIG_USER_BUSYBOX_FEATURE_SORT_BIG=y
# CONFIG_USER_BUSYBOX_SPLIT is not set
# CONFIG_USER_BUSYBOX_STAT is not set
CONFIG_USER_BUSYBOX_STTY=y
# CONFIG_USER_BUSYBOX_SUM is not set
CONFIG_USER_BUSYBOX_SYNC=y
# CONFIG_USER_BUSYBOX_TAC is not set
CONFIG_USER_BUSYBOX_TAIL=y
CONFIG_USER_BUSYBOX_FEATURE_FANCY_TAIL=y
CONFIG_USER_BUSYBOX_TEE=y
# CONFIG_USER_BUSYBOX_FEATURE_TEE_USE_BLOCK_IO is not set
CONFIG_USER_BUSYBOX_TEST=y
# CONFIG_USER_BUSYBOX_FEATURE_TEST_64 is not set
CONFIG_USER_BUSYBOX_TOUCH=y
CONFIG_USER_BUSYBOX_TR=y
# CONFIG_USER_BUSYBOX_FEATURE_TR_CLASSES is not set
# CONFIG_USER_BUSYBOX_FEATURE_TR_EQUIV is not set
CONFIG_USER_BUSYBOX_TRUE=y
CONFIG_USER_BUSYBOX_TTY=y
CONFIG_USER_BUSYBOX_UNAME=y
# CONFIG_USER_BUSYBOX_UNEXPAND is not set
CONFIG_USER_BUSYBOX_UNIQ=y
CONFIG_USER_BUSYBOX_USLEEP=y
CONFIG_USER_BUSYBOX_UUDECODE=y
CONFIG_USER_BUSYBOX_UUENCODE=y
CONFIG_USER_BUSYBOX_WC=y
# CONFIG_USER_BUSYBOX_FEATURE_WC_LARGE is not set
CONFIG_USER_BUSYBOX_WHO=y
CONFIG_USER_BUSYBOX_WHOAMI=y
CONFIG_USER_BUSYBOX_YES=y

#
# Common options for cp and mv
#
# CONFIG_USER_BUSYBOX_FEATURE_PRESERVE_HARDLINKS is not set

#
# Common options for ls, more and telnet
#
CONFIG_USER_BUSYBOX_FEATURE_AUTOWIDTH=y

#
# Common options for df, du, ls
#
CONFIG_USER_BUSYBOX_FEATURE_HUMAN_READABLE=y

#
# Common options for md5sum, sha1sum
#
# CONFIG_USER_BUSYBOX_FEATURE_MD5_SHA1_SUM_CHECK is not set

#
# Console Utilities
#
CONFIG_USER_BUSYBOX_CHVT=y
CONFIG_USER_BUSYBOX_CLEAR=y
# CONFIG_USER_BUSYBOX_DEALLOCVT is not set
# CONFIG_USER_BUSYBOX_DUMPKMAP is not set
# CONFIG_USER_BUSYBOX_KBD_MODE is not set
# CONFIG_USER_BUSYBOX_LOADFONT is not set
# CONFIG_USER_BUSYBOX_LOADKMAP is not set
CONFIG_USER_BUSYBOX_OPENVT=y
CONFIG_USER_BUSYBOX_RESET=y
CONFIG_USER_BUSYBOX_RESIZE=y
CONFIG_USER_BUSYBOX_FEATURE_RESIZE_PRINT=y
CONFIG_USER_BUSYBOX_SETCONSOLE=y
# CONFIG_USER_BUSYBOX_FEATURE_SETCONSOLE_LONG_OPTIONS is not set
# CONFIG_USER_BUSYBOX_SETKEYCODES is not set
# CONFIG_USER_BUSYBOX_SETLOGCONS is not set

#
# Debian Utilities
#
CONFIG_USER_BUSYBOX_MKTEMP=y
# CONFIG_USER_BUSYBOX_PIPE_PROGRESS is not set
# CONFIG_USER_BUSYBOX_RUN_PARTS is not set
# CONFIG_USER_BUSYBOX_START_STOP_DAEMON is not set
CONFIG_USER_BUSYBOX_WHICH=y

#
# Editors
#
CONFIG_USER_BUSYBOX_AWK=y
CONFIG_USER_BUSYBOX_FEATURE_AWK_MATH=y
CONFIG_USER_BUSYBOX_CMP=y
CONFIG_USER_BUSYBOX_DIFF=y
CONFIG_USER_BUSYBOX_FEATURE_DIFF_BINARY=y
CONFIG_USER_BUSYBOX_FEATURE_DIFF_DIR=y
# CONFIG_USER_BUSYBOX_FEATURE_DIFF_MINIMAL is not set
# CONFIG_USER_BUSYBOX_ED is not set
CONFIG_USER_BUSYBOX_PATCH=y
CONFIG_USER_BUSYBOX_SED=y
CONFIG_USER_BUSYBOX_VI=y
CONFIG_USER_BUSYBOX_FEATURE_VI_MAX_LEN=4096
CONFIG_USER_BUSYBOX_FEATURE_VI_8BIT=y
CONFIG_USER_BUSYBOX_FEATURE_VI_COLON=y
CONFIG_USER_BUSYBOX_FEATURE_VI_YANKMARK=y
CONFIG_USER_BUSYBOX_FEATURE_VI_SEARCH=y
CONFIG_USER_BUSYBOX_FEATURE_VI_USE_SIGNALS=y
CONFIG_USER_BUSYBOX_FEATURE_VI_DOT_CMD=y
CONFIG_USER_BUSYBOX_FEATURE_VI_READONLY=y
CONFIG_USER_BUSYBOX_FEATURE_VI_SETOPTS=y
CONFIG_USER_BUSYBOX_FEATURE_VI_SET=y
CONFIG_USER_BUSYBOX_FEATURE_VI_WIN_RESIZE=y
CONFIG_USER_BUSYBOX_FEATURE_VI_OPTIMIZE_CURSOR=y
CONFIG_USER_BUSYBOX_FEATURE_ALLOW_EXEC=y

#
# Finding Utilities
#
CONFIG_USER_BUSYBOX_FIND=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_PRINT0=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_MTIME=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_MMIN=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_PERM=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_TYPE=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_XDEV=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_MAXDEPTH=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_NEWER=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_INUM=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_EXEC=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_USER=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_GROUP=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_NOT=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_DEPTH=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_PAREN=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_SIZE=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_PRUNE=y
# CONFIG_USER_BUSYBOX_FEATURE_FIND_DELETE is not set
CONFIG_USER_BUSYBOX_FEATURE_FIND_PATH=y
CONFIG_USER_BUSYBOX_FEATURE_FIND_REGEX=y
CONFIG_USER_BUSYBOX_GREP=y
CONFIG_USER_BUSYBOX_FEATURE_GREP_EGREP_ALIAS=y
CONFIG_USER_BUSYBOX_FEATURE_GREP_FGREP_ALIAS=y
CONFIG_USER_BUSYBOX_FEATURE_GREP_CONTEXT=y
CONFIG_USER_BUSYBOX_XARGS=y
# CONFIG_USER_BUSYBOX_FEATURE_XARGS_SUPPORT_CONFIRMATION is not set
# CONFIG_USER_BUSYBOX_FEATURE_XARGS_SUPPORT_QUOTES is not set
# CONFIG_USER_BUSYBOX_FEATURE_XARGS_SUPPORT_TERMOPT is not set
# CONFIG_USER_BUSYBOX_FEATURE_XARGS_SUPPORT_ZERO_TERM is not set

#
# Init Utilities
#
# CONFIG_USER_BUSYBOX_INIT is not set
CONFIG_USER_BUSYBOX_HALT=y
# CONFIG_USER_BUSYBOX_MESG is not set

#
# Login/Password Management Utilities
#
CONFIG_USER_BUSYBOX_FEATURE_SHADOWPASSWDS=y
# CONFIG_USER_BUSYBOX_USE_BB_PWD_GRP is not set
CONFIG_USER_BUSYBOX_ADDGROUP=y
CONFIG_USER_BUSYBOX_FEATURE_ADDUSER_TO_GROUP=y
# CONFIG_USER_BUSYBOX_DELGROUP is not set
# CONFIG_USER_BUSYBOX_FEATURE_CHECK_NAMES is not set
CONFIG_USER_BUSYBOX_ADDUSER=y
# CONFIG_USER_BUSYBOX_FEATURE_ADDUSER_LONG_OPTIONS is not set
CONFIG_USER_BUSYBOX_DELUSER=y
# CONFIG_USER_BUSYBOX_GETTY is not set
CONFIG_USER_BUSYBOX_FEATURE_UTMP=y
# CONFIG_USER_BUSYBOX_LOGIN is not set
# CONFIG_USER_BUSYBOX_PASSWD is not set
# CONFIG_USER_BUSYBOX_CRYPTPW is not set
# CONFIG_USER_BUSYBOX_CHPASSWD is not set
# CONFIG_USER_BUSYBOX_SU is not set
# CONFIG_USER_BUSYBOX_SULOGIN is not set
# CONFIG_USER_BUSYBOX_VLOCK is not set

#
# Linux Ext2 FS Progs
#
# CONFIG_USER_BUSYBOX_CHATTR is not set
# CONFIG_USER_BUSYBOX_FSCK is not set
# CONFIG_USER_BUSYBOX_LSATTR is not set

#
# Linux Module Utilities
#
# CONFIG_USER_BUSYBOX_INSMOD is not set
# CONFIG_USER_BUSYBOX_RMMOD is not set
# CONFIG_USER_BUSYBOX_LSMOD is not set
# CONFIG_USER_BUSYBOX_MODPROBE is not set

#
# Linux System Utilities
#
CONFIG_USER_BUSYBOX_DMESG=y
CONFIG_USER_BUSYBOX_FEATURE_DMESG_PRETTY=y
# CONFIG_USER_BUSYBOX_FBSET is not set
# CONFIG_USER_BUSYBOX_FDFLUSH is not set
# CONFIG_USER_BUSYBOX_FDFORMAT is not set
# CONFIG_USER_BUSYBOX_FDISK is not set
# CONFIG_USER_BUSYBOX_FINDFS is not set
CONFIG_USER_BUSYBOX_FLOCK=y
# CONFIG_USER_BUSYBOX_FREERAMDISK is not set
# CONFIG_USER_BUSYBOX_FSCK_MINIX is not set
# CONFIG_USER_BUSYBOX_MKFS_MINIX is not set
CONFIG_USER_BUSYBOX_GETOPT=y
CONFIG_USER_BUSYBOX_HEXDUMP=y
# CONFIG_USER_BUSYBOX_FEATURE_HEXDUMP_REVERSE is not set
CONFIG_USER_BUSYBOX_HD=y
# CONFIG_USER_BUSYBOX_HWCLOCK is not set
# CONFIG_USER_BUSYBOX_IPCRM is not set
# CONFIG_USER_BUSYBOX_IPCS is not set
# CONFIG_USER_BUSYBOX_LOSETUP is not set
# CONFIG_USER_BUSYBOX_MDEV is not set
# CONFIG_USER_BUSYBOX_MKSWAP is not set
CONFIG_USER_BUSYBOX_MORE=y
CONFIG_USER_BUSYBOX_FEATURE_USE_TERMIOS=y
# CONFIG_USER_BUSYBOX_VOLUMEID is not set
CONFIG_USER_BUSYBOX_MOUNT=y
# CONFIG_USER_BUSYBOX_FEATURE_MOUNT_FAKE is not set
# CONFIG_USER_BUSYBOX_FEATURE_MOUNT_VERBOSE is not set
# CONFIG_USER_BUSYBOX_FEATURE_MOUNT_HELPERS is not set
# CONFIG_USER_BUSYBOX_FEATURE_MOUNT_LABEL is not set
CONFIG_USER_BUSYBOX_FEATURE_MOUNT_NFS=y
# CONFIG_USER_BUSYBOX_FEATURE_MOUNT_CIFS is not set
CONFIG_USER_BUSYBOX_FEATURE_MOUNT_FLAGS=y
CONFIG_USER_BUSYBOX_FEATURE_MOUNT_FSTAB=y
# CONFIG_USER_BUSYBOX_PIVOT_ROOT is not set
# CONFIG_USER_BUSYBOX_RDATE is not set
# CONFIG_USER_BUSYBOX_READPROFILE is not set
# CONFIG_USER_BUSYBOX_RTCWAKE is not set
# CONFIG_USER_BUSYBOX_SETARCH is not set
# CONFIG_USER_BUSYBOX_SWAPONOFF is not set
# CONFIG_USER_BUSYBOX_SWITCH_ROOT is not set
CONFIG_USER_BUSYBOX_UMOUNT=y
# CONFIG_USER_BUSYBOX_FEATURE_UMOUNT_ALL is not set

#
# Common options for mount/umount
#
CONFIG_USER_BUSYBOX_FEATURE_MOUNT_LOOP=y
# CONFIG_USER_BUSYBOX_FEATURE_MTAB_SUPPORT is not set

#
# Miscellaneous Utilities
#
# CONFIG_USER_BUSYBOX_ADJTIMEX is not set
# CONFIG_USER_BUSYBOX_BBCONFIG is not set
# CONFIG_USER_BUSYBOX_CHAT is not set
# CONFIG_USER_BUSYBOX_CHRT is not set
CONFIG_USER_BUSYBOX_CROND=y
# CONFIG_USER_BUSYBOX_DEBUG_CROND_OPTION is not set
# CONFIG_USER_BUSYBOX_FEATURE_CROND_CALL_SENDMAIL is not set
CONFIG_USER_BUSYBOX_CRONTAB=y
CONFIG_USER_BUSYBOX_DC=y
# CONFIG_USER_BUSYBOX_DEVFSD is not set
# CONFIG_USER_BUSYBOX_FEATURE_DEVFS is not set
# CONFIG_USER_BUSYBOX_EJECT is not set
# CONFIG_USER_BUSYBOX_LAST is not set
CONFIG_USER_BUSYBOX_LESS=y
CONFIG_USER_BUSYBOX_FEATURE_LESS_MAXLINES=9999999
CONFIG_USER_BUSYBOX_FEATURE_LESS_BRACKETS=y
CONFIG_USER_BUSYBOX_FEATURE_LESS_FLAGS=y
CONFIG_USER_BUSYBOX_FEATURE_LESS_FLAGCS=y
# CONFIG_USER_BUSYBOX_FEATURE_LESS_MARKS is not set
# CONFIG_USER_BUSYBOX_FEATURE_LESS_REGEXP is not set
# CONFIG_USER_BUSYBOX_HDPARM is not set
# CONFIG_USER_BUSYBOX_MAKEDEVS is not set
# CONFIG_USER_BUSYBOX_MICROCOM is not set
# CONFIG_USER_BUSYBOX_MOUNTPOINT is not set
# CONFIG_USER_BUSYBOX_MT is not set
# CONFIG_USER_BUSYBOX_RAIDAUTORUN is not set
# CONFIG_USER_BUSYBOX_RUNLEVEL is not set
CONFIG_USER_BUSYBOX_RX=y
CONFIG_USER_BUSYBOX_SCRIPT=y
# CONFIG_USER_BUSYBOX_STRINGS is not set
# CONFIG_USER_BUSYBOX_SETSID is not set
# CONFIG_USER_BUSYBOX_TASKSET is not set
CONFIG_USER_BUSYBOX_TIME=y
CONFIG_USER_BUSYBOX_TTYSIZE=y
CONFIG_USER_BUSYBOX_WATCHDOGD=y

#
# Networking Utilities
#
# CONFIG_USER_BUSYBOX_FEATURE_IPV6 is not set
# CONFIG_USER_BUSYBOX_VERBOSE_RESOLUTION_ERRORS is not set
# CONFIG_USER_BUSYBOX_ARP is not set
CONFIG_USER_BUSYBOX_ARPING=y
# CONFIG_USER_BUSYBOX_BRCTL is not set
# CONFIG_USER_BUSYBOX_DNSD is not set
# CONFIG_USER_BUSYBOX_ETHER_WAKE is not set
# CONFIG_USER_BUSYBOX_FAKEIDENTD is not set
# CONFIG_USER_BUSYBOX_FTPGET is not set
# CONFIG_USER_BUSYBOX_FTPPUT is not set
CONFIG_USER_BUSYBOX_HOSTNAME=y
# CONFIG_USER_BUSYBOX_HTTPD is not set
# CONFIG_USER_BUSYBOX_IFCONFIG is not set
# CONFIG_USER_BUSYBOX_IFENSLAVE is not set
# CONFIG_USER_BUSYBOX_IFUPDOWN is not set
# CONFIG_USER_BUSYBOX_INETD is not set
# CONFIG_USER_BUSYBOX_IP is not set
CONFIG_USER_BUSYBOX_IPCALC=y
CONFIG_USER_BUSYBOX_FEATURE_IPCALC_FANCY=y
CONFIG_USER_BUSYBOX_FEATURE_IPCALC_LONG_OPTIONS=y
# CONFIG_USER_BUSYBOX_NAMEIF is not set
# CONFIG_USER_BUSYBOX_NC is not set
CONFIG_USER_BUSYBOX_NETSTAT=y
# CONFIG_USER_BUSYBOX_FEATURE_NETSTAT_WIDE is not set
CONFIG_USER_BUSYBOX_NSLOOKUP=y
# CONFIG_USER_BUSYBOX_PING is not set
# CONFIG_USER_BUSYBOX_PSCAN is not set
# CONFIG_USER_BUSYBOX_ROUTE is not set
# CONFIG_USER_BUSYBOX_SENDMAIL is not set
# CONFIG_USER_BUSYBOX_FETCHMAIL is not set
# CONFIG_USER_BUSYBOX_SLATTACH is not set
CONFIG_USER_BUSYBOX_TELNET=y
CONFIG_USER_BUSYBOX_FEATURE_TELNET_TTYPE=y
CONFIG_USER_BUSYBOX_FEATURE_TELNET_AUTOLOGIN=y
# CONFIG_USER_BUSYBOX_TELNETD is not set
# CONFIG_USER_BUSYBOX_TFTP is not set
# CONFIG_USER_BUSYBOX_TFTPD is not set
# CONFIG_USER_BUSYBOX_TRACEROUTE is not set
CONFIG_USER_BUSYBOX_APP_UDHCPD=y
# CONFIG_USER_BUSYBOX_APP_DHCPRELAY is not set
CONFIG_USER_BUSYBOX_APP_DUMPLEASES=y
CONFIG_USER_BUSYBOX_FEATURE_UDHCPD_WRITE_LEASES_EARLY=y
CONFIG_USER_BUSYBOX_DHCPD_LEASES_FILE="/var/lib/misc/udhcpd.leases"
CONFIG_USER_BUSYBOX_APP_UDHCPC=y
# CONFIG_USER_BUSYBOX_FEATURE_UDHCPC_ARPING is not set
# CONFIG_USER_BUSYBOX_FEATURE_UDHCP_PORT is not set
# CONFIG_USER_BUSYBOX_FEATURE_UDHCP_DEBUG is not set
# CONFIG_USER_BUSYBOX_FEATURE_RFC3397 is not set
CONFIG_USER_BUSYBOX_DHCPC_DEFAULT_SCRIPT="/etc/scripts/udhcpc.script"
CONFIG_USER_BUSYBOX_UDHCPC_SLACK_FOR_BUGGY_SERVERS=80
# CONFIG_USER_BUSYBOX_VCONFIG is not set
CONFIG_USER_BUSYBOX_WGET=y
CONFIG_USER_BUSYBOX_FEATURE_WGET_STATUSBAR=y
CONFIG_USER_BUSYBOX_FEATURE_WGET_AUTHENTICATION=y
# CONFIG_USER_BUSYBOX_FEATURE_WGET_LONG_OPTIONS is not set
# CONFIG_USER_BUSYBOX_ZCIP is not set
# CONFIG_USER_BUSYBOX_TCPSVD is not set
# CONFIG_USER_BUSYBOX_UDPSVD is not set

#
# Process Utilities
#
CONFIG_USER_BUSYBOX_FREE=y
CONFIG_USER_BUSYBOX_FUSER=y
CONFIG_USER_BUSYBOX_KILL=y
CONFIG_USER_BUSYBOX_KILLALL=y
# CONFIG_USER_BUSYBOX_KILLALL5 is not set
# CONFIG_USER_BUSYBOX_NMETER is not set
CONFIG_USER_BUSYBOX_PGREP=y
CONFIG_USER_BUSYBOX_PIDOF=y
CONFIG_USER_BUSYBOX_FEATURE_PIDOF_SINGLE=y
CONFIG_USER_BUSYBOX_FEATURE_PIDOF_OMIT=y
CONFIG_USER_BUSYBOX_PKILL=y
CONFIG_USER_BUSYBOX_PS=y
CONFIG_USER_BUSYBOX_FEATURE_PS_WIDE=y
CONFIG_USER_BUSYBOX_RENICE=y
# CONFIG_USER_BUSYBOX_BB_SYSCTL is not set
# CONFIG_USER_BUSYBOX_TOP is not set
CONFIG_USER_BUSYBOX_UPTIME=y
CONFIG_USER_BUSYBOX_WATCH=y

#
# Shells
#
# CONFIG_USER_BUSYBOX_FEATURE_SH_IS_ASH is not set
# CONFIG_USER_BUSYBOX_FEATURE_SH_IS_HUSH is not set
# CONFIG_USER_BUSYBOX_FEATURE_SH_IS_MSH is not set
CONFIG_USER_BUSYBOX_FEATURE_SH_IS_NONE=y
# CONFIG_USER_BUSYBOX_ASH is not set
# CONFIG_USER_BUSYBOX_HUSH is not set
# CONFIG_USER_BUSYBOX_LASH is not set
# CONFIG_USER_BUSYBOX_MSH is not set
# CONFIG_USER_BUSYBOX_CTTYHACK is not set

#
# System Logging Utilities
#
CONFIG_USER_BUSYBOX_SYSLOGD=y
CONFIG_USER_BUSYBOX_FEATURE_ROTATE_LOGFILE=y
CONFIG_USER_BUSYBOX_FEATURE_REMOTE_LOG=y
# CONFIG_USER_BUSYBOX_FEATURE_SYSLOGD_DUP is not set
# CONFIG_USER_BUSYBOX_FEATURE_IPC_SYSLOG is not set
CONFIG_USER_BUSYBOX_KLOGD=y
CONFIG_USER_BUSYBOX_LOGGER=y

#
# Runit Utilities
#
# CONFIG_USER_BUSYBOX_RUNSV is not set
# CONFIG_USER_BUSYBOX_RUNSVDIR is not set
# CONFIG_USER_BUSYBOX_SV is not set
# CONFIG_USER_BUSYBOX_SVLOGD is not set
# CONFIG_USER_BUSYBOX_CHPST is not set
# CONFIG_USER_BUSYBOX_SETUIDGID is not set
# CONFIG_USER_BUSYBOX_ENVUIDGID is not set
# CONFIG_USER_BUSYBOX_ENVDIR is not set
# CONFIG_USER_BUSYBOX_SOFTLIMIT is not set

#
# Print Utilities
#
# CONFIG_USER_BUSYBOX_LPD is not set
# CONFIG_USER_BUSYBOX_LPR is not set
# CONFIG_USER_BUSYBOX_LPQ is not set

#
# Tinylogin
#
# CONFIG_USER_TINYLOGIN_TINYLOGIN is not set

#
# Applets
#

#
# Features
#

#
# MicroWindows
#
# CONFIG_USER_MICROWIN is not set

#
# Compiling Options
#

#
# Libraries
#

#
# Demos
#

#
# Applications
#

#
# Settings
#

#
# Display Config
#

#
# Mouse/Touch Screen
#

#
# Keyboard
#

#
# Install These Applications
#

#
# Games
#
# CONFIG_USER_GAMES_ADVENT4 is not set
# CONFIG_USER_GAMES_DUNGEON is not set
# CONFIG_USER_GAMES_RUBIK is not set
# CONFIG_USER_GAMES_TAMA is not set

#
# Miscellaneous Configuration
#
CONFIG_USER_RAMIMAGE_NONE=y
# CONFIG_USER_RAMIMAGE_RAMFS64 is not set
# CONFIG_USER_RAMIMAGE_RAMFS128 is not set
# CONFIG_USER_RAMIMAGE_RAMFS256 is not set
# CONFIG_USER_RAMIMAGE_RAMFS512 is not set
# CONFIG_USER_RAMIMAGE_RAMFS1024 is not set
# CONFIG_USER_RAMIMAGE_RAMFS2048 is not set
# CONFIG_USER_RAMIMAGE_RAMFS8192 is not set
# CONFIG_USER_CGI_GENERIC is not set
# CONFIG_USER_CGIHTML is not set
# CONFIG_USER_DEMO_BUTTON is not set
# CONFIG_USER_DEMO_LATCH is not set
# CONFIG_USER_DEMO_MORSE is not set
# CONFIG_USER_DEMO_R2100 is not set
# CONFIG_POOR_ENTROPY is not set

#
# Debug Builds
#
# CONFIG_LIB_DEBUG is not set
# CONFIG_USER_DEBUG is not set

#
# Debug tools
#
# CONFIG_USER_TIMEPEG_TPT is not set

#
# Debug libraries
#
# CONFIG_LIB_LIBCCMALLOC is not set

#
# Automake Applications
#
CONFIG_USER_MODEMMANAGER=y
CONFIG_USER_MODEMMANAGER_ALLPLUGINS=y
# CONFIG_USER_AUTHTEST is not set
# CONFIG_USER_FREERADIUS is not set
CONFIG_USER_IFMETRIC=y
# CONFIG_USER_IW is not set
CONFIG_USER_KMOD=y
CONFIG_USER_KMOD_LIBKMOD=y
CONFIG_USER_KMOD_TOOLS=y
# CONFIG_USER_LIGHTTPD is not set
CONFIG_USER_LLDPD=y
CONFIG_USER_MF2B=y
CONFIG_USER_MSMTP_MSMTP=y
CONFIG_USER_MTDUTILS=y
CONFIG_USER_MTDUTILS_ERASE=y
CONFIG_USER_MTDUTILS_ERASEALL=y
# CONFIG_USER_MTDUTILS_LOCK is not set
# CONFIG_USER_MTDUTILS_UNLOCK is not set
# CONFIG_USER_MTDUTILS_FTL_CHECK is not set
# CONFIG_USER_MTDUTILS_FTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_MKFSJFFS is not set
CONFIG_USER_MTDUTILS_MKFSJFFS2=y
# CONFIG_USER_MTDUTILS_NFTLDUMP is not set
# CONFIG_USER_MTDUTILS_NFTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_NANDDUMP is not set
# CONFIG_USER_MTDUTILS_NANDTEST is not set
# CONFIG_USER_MTDUTILS_NANDWRITE is not set
# CONFIG_USER_MTDUTILS_DOC_LOADBIOS is not set
# CONFIG_USER_MTDUTILS_DOC_LOADIPL is not set
CONFIG_USER_ODHCP6C=y
CONFIG_USER_OPENLDAP=y
CONFIG_USER_OPENRESOLV=y
CONFIG_USER_PAM_TACPLUS=y
CONFIG_LIB_LIBTAC=y
# CONFIG_USER_PCMCIAUTILS is not set
# CONFIG_USER_PSSH is not set
# CONFIG_USER_PYASN1 is not set
# CONFIG_USER_PYSNMP is not set
# CONFIG_USER_PYTHON is not set
CONFIG_USER_SHELLINABOX=y
# CONFIG_USER_SNORT_BARNYARD is not set
# CONFIG_USER_SOCAT is not set

#
# OpenSSH
#
CONFIG_USER_SSH_SSH=y
CONFIG_USER_SSH_SCP=y
CONFIG_USER_SSH_SFTP=y
# CONFIG_USER_SSH_SSH_KEYSIGN is not set
CONFIG_USER_SSH_SSHD=y
CONFIG_USER_SSH_SFTP_SERVER=y
CONFIG_USER_SSH_SSHKEYGEN=y

#
# Legacy/insecure options:
#
# CONFIG_USER_SSH_ONLY_RSA_V2_KEYGEN is not set
CONFIG_USER_SSH_SSH1=y
CONFIG_USER_SUDO=y
# CONFIG_USER_SYSFSUTILS is not set
CONFIG_USER_TFTP_HPA=y
CONFIG_USER_TRACEROUTE=y
CONFIG_USER_UDEV_GUDEV=y
# CONFIG_USER_UHUBCTL is not set
CONFIG_USER_USBUTILS=y
CONFIG_USER_UTIL_LINUX=y
CONFIG_USER_UTIL_LINUX_LIBBLKID=y
CONFIG_USER_UTIL_LINUX_LIBUUID=y
# CONFIG_USER_UTIL_LINUX_LIBMOUNT is not set
