#!/bin/sh
#
# Restart daemons that need to be started after the interface is configured
#
if [ -x /bin/ntpd -a -f /etc/ntpd.conf ]; then
	pkill -15 ntpd >& /dev/null	
	echo "Starting NTP Daemon"
	/bin/ntpd -s &
fi
if [ -x /bin/upsd ]; then
	sh /etc/scripts/upsctl restart
fi
if [ -x /bin/ifprobe ]; then
	/bin/ifprobe >& /dev/null &
fi
if [ -d /var/run/cms ]; then
	killall -HUP ssh
	/bin/config -r cmsbridges >& /dev/null &
fi
if [ -x /bin/ipsec -a -f /etc/config/ipsec.config.conf ]; then
	/bin/ipsec setup restart
fi
if [ -x /bin/ez-ipupdate ]; then
	killall -10 ez-ipupdate
fi
if [ -f /var/run/portmanager.pid ]; then
	kill -HUP $(cat /var/run/portmanager.pid)
fi
#
# Re-run firewall rules for new configuration
#
sh /etc/rc.firewall
