#!/bin/bash
#

if [ -f /etc/config/.initialised ]; then
	exit 0
fi

touch /etc/config/.initialised

# Specific config initialisation for ACM500x

# If we've got a cellular modem, enable masquerading on it, and forward LAN to it
# Also, we forward LAN to VPN
if [ -d /var/run/.modem ]; then
	/bin/config -s config.firewall.dialout.masquerade.enabled=on -s config.firewall.wan.forwards.dialout=on -s config.firewall.wan.forwards.vpn=on -s config.firewall.vpn.forwards.wan=on 
	/bin/config -r forwards
fi

