#!/bin/bash
ADDR=$2

### IPv4 ###
BAN_BACKUP=/var/run/mf2b.rules

### IPv6 ###
BAN_BACKUP6=/var/run/mf2b6.rules

# Apply the ban to iptables.
case $1 in
	ban) iptables --append Fail2Ban --source $ADDR/32 --jump DROP ;;
	unban) iptables --delete Fail2Ban --source $ADDR/32 --jump DROP ;;
	ban6) ip6tables --append Fail2Ban --source $ADDR/128 --jump DROP ;;
	unban6) ip6tables --delete Fail2Ban --source $ADDR/128 --jump DROP ;;
esac

# Backup the rules into the respective .rules file.
# If this is reapplying the rules, run the command if a backup file exists.
case $1 in
	ban|unban) iptables --list-rules Fail2Ban | sed 's,^-N,-Z,;s,^,iptables ,' > $BAN_BACKUP;;
	ban6|unban6) ip6tables --list-rules Fail2Ban | sed 's,^-N,-Z,;s,^,ip6tables ,' > $BAN_BACKUP6;;
	apply) if [ -f $BAN_BACKUP ]; then sh $BAN_BACKUP 2> /dev/null; fi ;;
	apply6) if [ -f $BAN_BACKUP6 ]; then sh $BAN_BACKUP6 2> /dev/null; fi ;;
esac
