#!/bin/bash
#

if [ -f /etc/config/.initialised ]; then
	exit 0
fi

touch /etc/config/.initialised

# Specific config initialisation for ACM550x

# If we've got a cellular modem, enable masquerading on it, and forward Mgmt LAN and wifi if we have it.
# Also, we forward Mgmt LAN and Wifi to VPN
if [ -d /var/run/.modem ]; then
	/bin/config -s config.firewall.dialout.masquerade.enabled=on -s config.firewall.lan.forwards.dialout=on -s config.firewall.lan.forwards.vpn=on -s config.firewall.vpn.forwards.lan=on
	if /sbin/ifconfig wlan0 &> /dev/null; then
		/bin/config -s config.firewall.wlan.forwards.dialout=on -s config.firewall.wlan.forwards.vpn=on -s config.firewall.vpn.forwards.wlan=on
	fi
	/bin/config -r forwards
fi

