#!/bin/sh

# if we have infod, push all udhcpc parameters into infod. This
# allows it to interfae with an external application (eg. conman).
if [ -x /bin/infod_client ]
then
	/bin/infod_client -o push -p "udhcpc.$interface.argument" -d "${1:- }"

	/bin/infod_client -o push -p "udhcpc.$interface.interface" -d "${interface:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.ip" -d "${ip:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.siaddr" -d "${siaddr:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.sname" -d "${sname:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.boot_file" -d "${boot_file:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.subnet" -d "${subnet:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.timezone" -d "${timezone:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.router" -d "${router:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.timesvr" -d "${timesvr:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.namesvr" -d "${namesvr:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.dns" -d "${dns:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.logsvr" -d "${logsvr:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.cookiesvr" -d "${cookiesvr:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.lprsvr" -d "${lprsvr:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.hostname" -d "${hostname:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.bootsize" -d "${bootsize:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.domain" -d "${domain:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.swapsvr" -d "${swapsvr:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.rootpath" -d "${rootpath:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.ipttl" -d "${ipttl:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.mtu" -d "${mtu:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.broadcast" -d "${broadcast:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.ntpsrv" -d "${ntpsrv:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.wins" -d "${wins:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.lease" -d "${lease:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.dhcptype" -d "${dhcptype:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.serverid" -d "${serverid:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.message" -d "${message:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.tftp" -d "${tftp:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.bootfile" -d "${bootfile:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.vendorspec_1" -d "${vendorspec_1:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.vendorspec_2" -d "${vendorspec_2:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.vendorspec_3" -d "${vendorspec_3:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.vendorspec_4" -d "${vendorspec_4:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.vendorspec_5" -d "${vendorspec_5:- }"
	/bin/infod_client -o push -p "udhcpc.$interface.vendorspec_6" -d "${vendorspec_6:- }"

	if [ "$1" = "renew" -o "$1" = "bound" ]
	then
		/bin/infod_client -o push -p "udhcpc.$interface.status" -d "up"
	fi
	if [ "$1" = "deconfig" ]
	then
		/bin/infod_client -o push -p "udhcpc.$interface.status" -d "down"
	fi

fi
