#!/bin/sh

[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="/$subnet"

case $1 in
	deconfig)
		/bin/ip addr del $ip dev $interface
		;;

	renew|bound)
		# Remove duplicate IP assigned by ipsetd
		interface2=`echo $interface | cut -f1 -d':'`:1
		ip2=`/bin/ip addr show $interface | grep $interface2 | cut -f6 -d' ' | cut -f1 -d'/'`
		[ "$ip2" = "$ip" ] && /bin/ip addr del $ip2 dev $interface label $interface2

		# Set DHCP address
		/bin/ip addr add $ip$NETMASK $BROADCAST dev $interface

		# Restart network daemons on configuration change
		envfile=/var/run/udhcpc-${interface}.env
		tmpfile=${envfile}.$$

		trap "mv $tmpfile $envfile" EXIT
		env > $tmpfile

		if [ "$RUNNING_UNDER_CONMAN" != "yes" ]; then
			if ! cmp $envfile $tmpfile >& /dev/null ; then
				sh /etc/ifup
			fi
		fi
		;;
esac
exit 0
