#
# Makefile for the kernel auxiliary displays device drivers.
#

obj-$(CONFIG_KS0108)		+= ks0108.o
obj-$(CONFIG_CFAG12864B)	+= cfag12864b.o cfag12864bfb.o
obj-$(CONFIG_CFAX128)		+= cfax128fb.o nt7534.o
