#!/bin/sh

if [ -z "$ALERT_XMLID" -o -z "$ALERT_PORT" -o -z "$ALERT_PORTNAME" \
		-o -z "$ALERT_USER" -o -z "$USER_EVENT" ]; then
	echo "Script does not have mandatory environment"
	exit 1
fi

# If there's a user-configured script, run it instead
scripts[0]="/etc/config/scripts/user-alert.${ALERT_PORTNAME}"
scripts[1]="/etc/config/scripts/portmanager-user-alert"
for (( i=0 ; i < ${#scripts[@]} ; i++ )); do
	if [ -f "${scripts[$i]}" ]; then
		exec /bin/sh "${scripts[$i]}"
	fi
done

retval=0

nsca=$(config -g $ALERT_XMLID.nsca.enabled | cut -f2- -d' ')
if [ "$nsca" == "on" ]; then

	export NAME="$(config -g config.ports.port$ALERT_PORT.nagios.name | cut -f2- -d' ')"
	export CODE="1"
	export CHECK="alert_login_$NAME"
	export STATUS="The user \"$ALERT_USER\" has performed a \"$USER_EVENT\" on port $ALERT_PORT"

	/bin/sh /etc/scripts/alert-nsca
	retval=$(( $? || $retval ))
fi

snmp=$(config -g $ALERT_XMLID.snmp.enabled | cut -f2- -d' ')
if [ "$snmp" == "on" ]; then

	export OID="enterprises.opengear"
	export AGENT=""
	export UPTIME=""
	export SPECIFIC_TYPE=".ogConnectMib.ogConnectMibObjects.ogconnEvent.ogconnEventTable"
	export TRAP_NAME="ogconnEventOccurred"
	export NOTIFICATION_TYPE=".ogConnectMib.ogConnectMibNotificationPrefix.ogconnMibNotifications"

	/bin/sh /etc/scripts/alert-snmp \
		".ogconnEventEntry.ogconnEventUsername" \
		"s" \
		"$ALERT_USER" \
		".ogconnEventEntry.ogconnEventType" \
		"s" \
		"$USER_EVENT" \
		".ogconnEventEntry.ogconnEventPortNumber" \
		"i" \
		"$ALERT_PORT" \
		".ogconnEventEntry.ogconnEventPortLabel" \
		"s" \
		"$(config -g config.ports.port$ALERT_PORT.label | cut -f2- -d' ')"

	retval=$(( $? || $retval ))
fi

cms=$(config -g config.cms.enabled | cut -f2- -d' ')
if [ "$cms" == "on" ]; then
	alertnum=$(echo $ALERT_XMLID | sed 's/config.alerts.alert//')
	nodename=$(config -g config.cms.node.name | cut -f2- -d' ')
	/bin/run_check -c check_xmlalert_${alertnum}_${nodename}
	retval=$(( $? || $retval ))
fi

for suffix in "" "2"; do

	email=$(config -g $ALERT_XMLID.email$suffix | cut -f2- -d' ')
	if [ -z "$email" ]; then
		continue
	fi

	export SUBJECT="Alert on port $ALERT_PORT on $(hostname)"
	export TOADDR="$email"
	export BODY="User $ALERT_USER has performed a $USER_EVENT on port $ALERT_PORT"

	/bin/sh /etc/scripts/alert-email $suffix
	retval=$(( $? || $retval ))
done

exit $retval
