#!/bin/sh

LS="/bin/ls"
CUT="/usr/bin/cut"
EXPR="/usr/bin/expr"

get_octal() {
	RIGHTS=$1
	R=$(echo "$RIGHTS" | $CUT -c1)
	W=$(echo "$RIGHTS" | $CUT -c2)
	X=$(echo "$RIGHTS" | $CUT -c3)
	OCTAL="0"
	if [ "$R" == "r" ]; then
		OCTAL=$($EXPR $OCTAL + 4) 
	fi
	if [ "$W" == "w" ]; then
		OCTAL=$($EXPR $OCTAL + 2) 
	fi
	if [ "$X" == "x" ]; then
		OCTAL=$($EXPR $OCTAL + 1) 
	fi
	return $OCTAL
}

do_perms() {
	PATH=$1; USER=$2; GROUP=$3; UUU=$4; GGG=$5; OOO=$6;
	LIST=$($LS -l $PATH)
	ERROR=$(echo "$LIST" | $CUT -f3- -d' ')

	uuu=$(echo $LIST | $CUT -c2-4)
	ggg=$(echo $LIST | $CUT -c5-7)
	ooo=$(echo $LIST | $CUT -c8-10)
	if [ "$uuu" != "$UUU" -o "$ggg" != "$GGG" -o "$ooo" != "$OOO" ]; then
		get_octal $uuu; UR=$?;
		get_octal $ggg; GR=$?;
		get_octal $ooo; OR=$?;
		OCTAL="${UR}${GR}${OR}"
		echo "chmod $OCTAL $PATH"
	fi
	user=$(echo $LIST | $CUT -f3 -d' ')
	if [ "$user" != "$USER" ]; then
		echo "chown $USER $PATH"
	fi
	group=$(echo $LIST | $CUT -f4 -d' ')
	if [ "$group" != "$GROUP" ]; then
		echo "chgrp $GROUP $PATH"
	fi
}

# System files
do_perms "/etc/passwd" 		 		"root" "root"  "rw-" "r--" "r--"
do_perms "/etc/group" 		 		"root" "root"  "rw-" "r--" "r--"
do_perms "/etc/config" 		 		"root" "root"  "rwx" "r-x" "r-x"
do_perms "/etc/config/chap-secrets"  		"root" "root"  "rw-" "---" "---"
do_perms "/etc/config/pap-secrets"  		"root" "root"  "rw-" "---" "---"

# Opengear specific configuration files
do_perms "/etc/config/config.xml" 		"root" "admin" "rw-" "rw-" "r--"
do_perms "/bin/config" 				"root" "admin" "r-x" "r-x" "---"
do_perms "/home/httpd/cgi-bin/index.cgi"	"root" "admin" "r-x" "r-x" "---"
do_perms "/home/httpd/cgi-bin/netflash.cgi"	"root" "admin" "r-x" "r-x" "---"
