#!/bin/sh

PARTITIONS=`fdisk -l /dev/sda | grep sda1`
if [ -z "$PARTITIONS" ]; then
	USBDEV="/dev/sda"
else
	USBDEV="/dev/sda1"
fi

USBPATH="/tmp/usbdisk"

if [ ! -b "$USBDEV" ]; then
	exit 0
fi

tftpd=$(config -g config.services.tftp.enabled | cut -f2- -d' ')
ftpd=$(config -g config.services.ftp.enabled | cut -f2- -d' ')
if [ ! -z "$tftpd" -o ! -z "$ftpd" ]; then
	if [ ! -d "$USBPATH" ]; then
		mkdir -p $USBPATH
		if [ $? != 0 ]; then
			exit 1
		fi
	fi
	if [ ! -d $USBPATH/tftpboot ]; then
		mount -t vfat -o umask=022 $USBDEV $USBPATH
		if [ $? != 0 ]; then
			exit 1
		fi
		if [ ! -d $USBPATH/tftpboot ]; then
			mkdir $USBPATH/tftpboot
			if [ $? != 0 ]; then
				exit 1
			fi
		fi
	fi
fi

exit 0
