#!/bin/sh

# udhcpc script edited by Tim Riker <Tim@Rikers.org>

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

RESOLV_CONF="/var/run/${interface}-resolv.conf"
[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="netmask $subnet"

case "$1" in
	deconfig)
		/sbin/ifconfig $interface 0.0.0.0
		;;

	renew|bound)
		# Remove duplicate IP assigned by ipsetd
		ip2=`/sbin/ifconfig eth0:1 | grep inet\ addr | cut -f2 -d':' | cut -f1 -d' '`
		[ "$ip2" == "$ip" ] && /sbin/ifconfig eth0:1 down

		/sbin/ifconfig $interface $ip $BROADCAST $NETMASK
		
		if [ -n "$router" ] ; then
			echo "deleting routers"
			while route del default gw 0.0.0.0 dev $interface ; do
				:
			done

			if [ -f "/var/run/$interface-failed-over" ]; then
				metric=100
			else
				metric=0
			fi

			for i in $router ; do
				route add default gw $i dev $interface metric $((metric++))
			done
		fi

		echo -n > $RESOLV_CONF
		[ -n "$domain" ] && echo search $domain >> $RESOLV_CONF
		for i in $dns ; do
			echo adding dns $i
			echo nameserver $i >> $RESOLV_CONF
		done
		# Run resolvconf to update our resolv.conf
		cat $RESOLV_CONF | /bin/resolvconf -a $interface 

		# Restart network daemons on configuration change
		envfile=/var/run/udhcpc-${interface}.env
		tmpfile=${envfile}.$$

		trap "mv $tmpfile $envfile" EXIT
		env > $tmpfile

		if ! cmp $envfile $tmpfile >& /dev/null ; then
			sh /etc/ifup
		fi

		;;
esac

exit 0
