#! /bin/bash

# This script acts as a wrapper for deleting users using the 'config' command 
# in the CLI. The administrator provides the username(s) to delete
# and the script then invokes the CGI's directly to handle the actual
# deleting.
# see also "user-add" and "user-mod" scripts.

usage()
{
        echo 'usage: user-del [-h] username ...'
}

if [ $# -lt  1 ]
then
        echo "Provide at least one username"
        usage
        exit 1
fi

while getopts "h" OPTION                                                  
do                                                                              
        case "$OPTION" in                                                       
           h)                                                                   
                usage                                                           
                exit 1                                               
                ;;                                                   
           [?])                         
                usage                   
                exit                    
                ;;                 
         esac                      
done                

# Do a shift in order to retrieve the usernames in $@
shift $[ $OPTIND - 1]      

for USERNAME in $@
do
	# Test whether this user exists
	USEREXISTS=`grep -e "^$USERNAME:" /etc/passwd`
	if [ -z "$USEREXISTS" ]
	then
        	echo "Error: User \"$USERNAME\" does not exist. "
		exit 1
	fi
done

# Backup /etc/config.xml file
cp /etc/config/config.xml /etc/config/config.bak
echo "backup of /etc/config/config.xml saved in /etc/config/config.bak"

for USERNAME in $@
do
	echo "Deleting user $USERNAME"
	
	# Get the config index of the user.
	USERINDEX=`config -g config.users | grep -e \
	"config\.users\.user.*\.username $USERNAME$" | \
	sed 's/[a-zA-Z.]*\([0-9]*\).* .*/\1/'`

	if [ -z "$USERINDEX" ]
	then
		echo "Unable to delete user $USERNAME"
		echo "Does that user exist?"
	fi

	REQUEST_METHOD=GET REMOTE_USER=$(whoami) QUERY_STRING="form=users&action=del&index=$USERINDEX&type=user" /home/httpd/cgi-bin/index.cgi > /dev/null

done
	
#echo "Running configurators..."
#config -r users

echo
echo "done"

exit 0
