#!/bin/sh
#
# setup flash key for config filesystem
#
# usage: setup-flashkey /dev/sda
#
# David McCullough <davidm@opengear.com>
#

DEVICE="$1"

yesno()
{
	while :
	do
		echo -n "$1 (y/n) [$2]: "
		read t
		[ -z "$t" ] && t="$2"
		case "$t" in
		y*|Y*) return 0 ;;
		n*|N*) return 1 ;;
		esac
		echo "Please enter 'y' or 'n'"
	done
}

#
# the main routine
#

if [ ! -b "$DEVICE" ]; then
	echo
	echo "usage: $0 <block-device>"
	echo
	echo "Setup a usable config filesystem on a USB flash key."
	echo
	echo "Possible devices to use are:"
	dmesg | grep "SCSI device" | sed 's|^SCSI device |/dev/|'
	exit 1
fi

echo "**************************************"
echo
echo "Warning.  This will erase your flash drive."
echo
echo "**************************************"
echo
if ! yesno "Are you sure you want to continue ?" n
then
	exit 1
fi

sfdisk -uM $DEVICE <<!EOF
0,,61,-
,0,,-
,0,,-
,0,,-
!EOF

if [ "$?" != 0 ]
then
	echo "fdisk failed."
	exit 1
fi

echo "Making filesystems ..."
sleep 5

if ! mke2fs -j ${DEVICE}1
then
	echo "Failed to format config filesystem."
	exit 1
fi

#
# setup the config filesystem
#

mount ${DEVICE}1 /mnt
cp -r /etc/config /mnt
umount /mnt

echo
echo "Reboot to use new config filesystem properly."

exit 0
