#!/bin/bash

MODEM=$6

# If there's a user-configured script, run it instead
scripts[0]="/etc/config/scripts/dialout-up.${MODEM}"
scripts[1]="/etc/config/scripts/dialout-up"
for (( i=0 ; i < ${#scripts[@]} ; i++ )); do
        if [ -f "${scripts[$i]}" ]; then
                exec /bin/sh "${scripts[$i]}" "$@"
        fi
done

ip rule del table $IFNAME
ip route flush table $IFNAME

table=$(( 200 + $(echo $IFNAME | sed 's/dialout//') ))
sed -i "/.*${IFNAME}$/d" /etc/iproute2/rt_tables
echo "$table	$IFNAME" >> /etc/iproute2/rt_tables

ipaddr=$(ifconfig $IFNAME | grep inet\ addr | cut -f2 -d':' | cut -f1 -d' ')
ip route add default dev $IFNAME table $IFNAME
#ip rule add fwmark 1 table $IFNAME
#iptables -t mangle -A OUTPUT -s $ipaddr ! -o ipsec+ --jump MARK --set-mark 1

ip route add default dev $IFNAME metric 10

ln -sf /var/run/${IFNAME}.resolv /var/run/ppp-${MODEM}.resolv
# Push our resolv.conf into resolvconf 
if [ -f /etc/config/network/dialout.${MODEM}.resolv ]; then
	RESOLV=/etc/config/network/dialout.${MODEM}.resolv
else
	RESOLV=/var/run/${IFNAME}.resolv
fi

# Clear out existing cellmodem entries, just in case PPP died before 
# running the dialout-down script
/bin/resolvconfig -d ${MODEM}
cat $RESOLV | /bin/resolvconf -a ${MODEM}

sh /etc/scripts/ddns-up "$@"
sh /etc/ifup

if [ -x /bin/devlog ]; then
	/bin/devlog -i ${IFNAME} -p /var/run/devlog.${IFNAME}.pid --background
fi


# if we have infod, then push all the PPP reported variables into a ppp
# section of infod (against the device). clear any that are only relevant
# to ip-down scripts. (extracted from the pppd man page; all infod locations
# are based on the variable name in lower case.)
if [ -x /bin/infod_client ]
then
	/bin/infod_client -o push -p "config.$LINKNAME.status" -d "connected"

	/bin/infod_client -o push -p "config.$LINKNAME.ppp.device" -d "${DEVICE:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.ifname" -d "${IFNAME:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.iplocal" -d "${IPLOCAL:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.ipremote" -d "${IPREMOTE:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.peername" -d "${PEERNAME:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.speed" -d "${SPEED:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.orig_uid" -d "${ORIG_UID:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.ppplogname" -d "${PPPLOGNAME:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.connect_time" -d "${CONNECT_TIME:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.bytes_sent" -d "${BYTES_SENT:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.bytes_rcvd" -d "${BYTES_RCVD:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.linkname" -d "${LINKNAME:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.call_file" -d "${CALL_FILE:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.dns1" -d "${DNS1:- }"
	/bin/infod_client -o push -p "config.$LINKNAME.ppp.dns2" -d "${DNS2:- }"
fi

# Clear retry count on successful connection
rm -f /var/run/.modem/retry_count

