#!/bin/bash

MODEM=$6

# If there's a user-configured script, run it instead
scripts[0]="/etc/config/scripts/dialout-up.${MODEM}"
scripts[1]="/etc/config/scripts/dialout-up"
for (( i=0 ; i < ${#scripts[@]} ; i++ )); do
        if [ -f "${scripts[$i]}" ]; then
                exec /bin/sh "${scripts[$i]}" "$@"
        fi
done

ip rule del table $IFNAME
ip route flush table $IFNAME

table=$(( 200 + $(echo $IFNAME | sed 's/dialout//') ))
sed -i "/.*${IFNAME}$/d" /etc/iproute2/rt_tables
echo "$table	$IFNAME" >> /etc/iproute2/rt_tables

ipaddr=$(ifconfig $IFNAME | grep inet\ addr | cut -f2 -d':' | cut -f1 -d' ')
ip route add default dev $IFNAME table $IFNAME
ip rule add from $ipaddr table $IFNAME

ip route add default dev $IFNAME metric 10

ln -sf /var/run/${IFNAME}.resolv /var/run/ppp-${MODEM}.resolv
# Push our resolv.conf into resolvconf 
if [ -f /etc/config/network/dialout.${MODEM}.resolv ]; then
	RESOLV=/etc/config/network/dialout.${MODEM}.resolv
else
	RESOLV=/var/run/${IFNAME}.resolv
fi

cat $RESOLV | /bin/resolvconf -a ${MODEM}

sh /etc/scripts/ddns-up "$@"
sh /etc/ifup
