#!/bin/sh

if [ -z "$ALERT_XMLID" -o \
		-z "$ALERT_DEVICE_TYPE" -o \
		-z "$ALERT_DEVICE" -o \
		-z "$ALERT_OLD" -o \
		-z "$ALERT_NEW" -o \
		-z "$ALERT_VALUE" -o \
		-z "$ALERT_CODE" ]; then
	echo "Script does not have mandatory environment"
	exit 1
fi


# If there's a user-configured script, run it instead
scripts[0]="/etc/config/scripts/environmental-alert.${NODE_ID}"
scripts[1]="/etc/config/scripts/environmental-alert"
for (( i=0 ; i < ${#scripts[@]} ; i++ )); do
	if [ -f "${scripts[$i]}" ]; then
		exec /bin/sh "${scripts[$i]}"
	fi
done

retval=0

nsca=$(config -g $ALERT_XMLID.nsca.enabled | cut -f2- -d' ')
if [ "$nsca" == "on" ]; then

	export NAME=$ALERT_NAGNAME
	case "$ALERT_CODE"
	in
		"1"|"5")
			CODE=2
			;;
		"2"|"4")
			CODE=1
			;;
		"3")
			CODE=0
			;;
		*)
			CODE=3
			;;
	esac
		
	export CODE
	export CHECK="alert_enviro_$NAME"
	export STATUS="The $ALERT_SENSOR sensor is registering $ALERT_VALUE"

	/bin/sh /etc/scripts/alert-nsca
	retval=$(( $? || $retval ))
fi

snmp=$(config -g $ALERT_XMLID.snmp.enabled | cut -f2- -d' ')
if [ "$snmp" == "on" ]; then

	export OID="enterprises.opengear"
	export AGENT=""
	export UPTIME=""
	export SPECIFIC_TYPE=".ogSensorMib.ogSensorMibObjects.ogsensStatus.ogsensStatusTable"
	export TRAP_NAME="ogsensEventOccurred"
	export NOTIFICATION_TYPE=".ogSensorMib.ogSensorMibNotificationPrefix.ogsensMibNotifications"

	/bin/sh /etc/scripts/alert-snmp \
		".ogsensStatusEntry.ogsensStatusName" \
		"s" \
		"$ALERT_DEVICE" \
		".ogsensStatusEntry.ogsensStatusDevType" \
		"s" \
		"$ALERT_DEVICE_TYPE" \
		".ogsensStatusEntry.ogsensStatusType" \
		"s" \
		"$ALERT_SENSOR" \
		".ogsensStatusEntry.ogsensStatusValue" \
		"i" \
		"$ALERT_VALUE"

	retval=$(( $? || $retval ))
fi

cms=$(config -g config.cms.enabled | cut -f2- -d' ')
if [ "$cms" == "on" ]; then
	alertnum=$(echo $ALERT_XMLID | sed 's/config.alerts.alert//')
	nodename=$(config -g config.cms.node.name | cut -f2- -d' ')
	/bin/run_check -c check_xmlalert_${alertnum}_${nodename}
	retval=$(( $? || $retval ))
fi

for suffix in "" "2"; do

	email=$(config -g $ALERT_XMLID.email$suffix | cut -f2- -d' ')
	if [ -z "$email" ]; then
		continue
	fi

	export SUBJECT="Alert on $ALERT_DEVICE on $(hostname)"
	export TOADDR="$email"
	export BODY="The $ALERT_DEVICE_TYPE $ALERT_DEVICE has triggered an alarm condition: $ALERT_SENSOR of $ALERT_VALUE"

	/bin/sh /etc/scripts/alert-email $suffix
	retval=$(( $? || $retval ))
done

exit $retval
