#!/bin/sh

[ -z "$TIMEOUT" ] && TIMEOUT=30

lockdir="/tmp/$(basename "$0").lock"
pidfile="$lockdir/PID"
if mkdir "$lockdir"; then
	echo "$$" > "$pidfile"
	trap 'rm -rf "$lockdir"' 0
	trap "exit 0" 1 2 3 15
else
	timeout=$TIMEOUT
	signal=0
	while true; do
		pid="$(cat "$pidfile")"
		if [ -z "$pid" ] || ! kill -$signal $pid; then
			rm -rf "$lockdir"
			exec "$0" "$@"
		else
			echo "Failed to lock $lockdir" >&2
			if [ $(( timeout-- )) -eq 0 ]; then
				echo "Killing $pid" >&2
				signal=9
			else
				sleep 1
			fi
		fi
	done
fi
