#!/bin/bash

function restart() {
	/etc/config/scripts/dummy-console $portnum \
		< /dev/.dummy-console-$portnum \
		> /dev/.dummy-console-$portnum &
	exit 0
}

trap restart HUP

portnum=$1

echo $$ > /var/run/.dummy-console-${portnum}.pid

while [[ -f /var/run/.dummy-console-${portnum}-off ]]; do
	sleep 1
done

sleep 5
echo "Boot Loader (BOOT) Version 4.3.2.1"
echo "Compiled Mon 01-Jan-12 12:34 by nobody"
echo "Initializing..."
sleep 5
echo "Press RETURN to get started."

label=$(config -g config.ports.port${portnum}.label | cut -f2 -d' ')
read -t 1 -n 9999 discard
while read line; do
	if [ -n "$line" ]; then
		case "$line" in
		help*)
			echo "% This is a simulated managed console for demo purposes, for a live demo please contact us!"
			;;
		*)
			echo "Unknown command: $line"
			;;
		esac
	fi
	echo -n "${label}>"
done
