#!/bin/bash

cmdset="reset|ping|oobfo-port-start|oobfo-port-stop|management-lan-start|management-lan-stop|clear"
retval=0

if [[ -z "${switch_mac}" ]]; then
	switch_mac="00:00:00:00:00:00"
fi
if [[ -z "${switch_if}" ]]; then
	switch_if="eth1"
fi

function ping () {
	retries=30
	for (( i=0; i < $retries; i++ )); do
		if rtl8326 $switch_mac@$switch_if ping &> /dev/null; then
			retval=$(( 0 || $retval ))
			return
		fi
	done
	echo "No switch detected at ${switch_mac}@${switch_if}"
	retval=1
}

function management-lan-stop () {
	rtl8326 ${switch_mac}@${switch_if} config interface 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 shutdown &> /dev/null
	retval=$(( $? || $retval ))
	disabled=$(config -g config.interfaces.oobfo.disabled | cut -f2- -d' ')
	if [[ -n "${disabled}" ]]; then
		oobfo-port-stop
		retval=$(( $? || $retval ))
	fi
}

function management-lan-start () {
	rtl8326 ${switch_mac}@${switch_if} config interface 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 no shutdown &> /dev/null
	retval=$(( $? || $retval ))
	disabled=$(config -g config.interfaces.oobfo.disabled | cut -f2- -d' ')
	if [[ -n "${disabled}" ]]; then
		oobfo-port-start
		retval=$(( $? || $retval ))
	fi
}

function oobfo-port-stop () {
	rtl8326 ${switch_mac}@${switch_if} config interface 24 shutdown &> /dev/null
	retval=$(( $? || $retval ))
}

function oobfo-port-start () {
	rtl8326 ${switch_mac}@${switch_if} config interface 24 no shutdown &> /dev/null
	retval=$(( $? || $retval ))
}

function reset () {
	rtl8326 ${switch_mac}@${switch_if} config interface 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24 shutdown &> /dev/null
	retval=$(( $? || $retval ))
	rtl8326 ${switch_mac}@${switch_if} config interface 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24 rrcp disable &> /dev/null
	retval=$(( $? || $retval ))
	rtl8326 ${switch_mac}@${switch_if} config vlan mode portbased &> /dev/null
	retval=$(( $? || $retval ))
}

function clear () {
	rtl8326 ${switch_mac}@${switch_if} config interface 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24 no shutdown &> /dev/null
	retval=$(( $? || $retval ))
	rtl8326 ${switch_mac}@${switch_if} config vlan disable &> /dev/null
	retval=$(( $? || $retval ))
}

function ifup () {
	if ! ifconfig -s | grep $switch_if &> /dev/null ; then
		ifconfig $switch_if up	
		bring_down_if="true"
	fi
	if [ $cmd != "ping" ]; then
		# Ensure the interface is actually up
		ping
	fi
}

function ifdown () {
	if [[ -n "${bring_down_if}" ]] ; then
		ifconfig $switch_if down
	fi
}

if [[ $# -eq 0 ]] ; then
	cmd="ping"
else
	cmd="$1"
fi

if echo "$cmdset" | grep "$cmd" &> /dev/null ; then
	ifup
	$cmd
	ifdown
else
	echo "Usage: $0 $cmdset"
	retval=1
fi

exit $retval
